### ISSUE TITLE
Did Subscribe doesn't support parameter and callback in react-native-meteor 1.0.0-beta?

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#10]
Although I am not yet successfully using this package, I have take a look at the src code. The subscribe method doesn't have parameter or callback if I am not wrong. 
Please add ability to make subscribe able to receive parameter and using callback. 
If it's already there, please give example how to do that

**Comment by Mokto** [comment]
Subscribe accepts parameters but not callbacks yet. Will be adding it soon.

**Comment by radiegtya** [comment]
Subscribe with parameter, is working just fine, and I think callback not a must feature. The more important is this issue https://github.com/inProgress-team/react-native-meteor/issues/7. I'll close this for now, but please support those issue. Thanks
