### ISSUE TITLE
Secured wss:// protocol failing ?

### ISSUE THREAD

**Issue by teknologist** [inProgress-team/react-native-meteor#100]
I was wondering if the wss encrypted websocket protocol was implemented.

I can't seem to make it work and haven't seen anything in the code related to encryption.

oortcloud/node-ddp-client seems to have encryption support.

was just wondering...

**Comment by fermuch** [comment]
It works out-of-the-box since it's part of the websocket implementation, not react-native-meteor.
I only use wss with my servers, for example.

**Comment by teknologist** [comment]
Thanks for the help!
It was due to /websocket not being proxy-ed as a websocket on nginx. I only had setup websocket proxying for /sockjs
