### ISSUE TITLE
Passing pagingEnabled props to MeteorListView not working on Android

### ISSUE THREAD

**Issue by donedgardo** [inProgress-team/react-native-meteor#102]
Using latest version of react-native-meteor and react-native@0.28

This is my code 
```javascript
<MeteorListView
         collection={'news'}
         onScroll={this.setRenderedNewsIndex}
         options={{sort: {created_at: -1}}}
         pagingEnabled={true}
         renderRow={this.renderRow}
         scrollEventThrottle={10000}
         selector={{}}
         showsVerticalScrollIndicator={false}
 />
```
It works fine in ios but not on Android.
On android  scrolling works fine and all elements are rendered but not as intended(paginated).

At first I thought it didn't work because I had a previous version of react-native (0.26) that didn't support the props `pagingEnabled` I upgraded to 0.28 but still no success.

Does MeteorList support pagingEnabled for android?

**Comment by Mokto** [comment]
Hi,

I don't understand why this would not work with react-native-meteor.
I'm passing down all the props to the ListView component.

But I have never used this property.
