### ISSUE TITLE
re render MeteorComplexListView based on a change in state.

### ISSUE THREAD

**Issue by sepehrooo** [inProgress-team/react-native-meteor#108]
I have a MeteorComplexListView and I want to give dynamic styling to it's list items.
for example when a list item got touched, I want to give that specific list item a background color to show it is active.

I thought in renderRow I could do this:
`const style = this.state.itemId == item._id ? { color: 'red' } : {};`

    return (
      <TouchableHighlight style={[styles.buttons, style]} onPress={() => {
        this.setState({ itemId: item._id })
        this.setState({ subitem: {} })
      }}>
        <Text>{item.text}</Text>
      </TouchableHighlight>
    );

but this won't re render the listView and nothing happens.

Any ideas?

**Comment by funkyeah** [comment]
Can you get it to work with the standard react-native listView? It doesn't look like this issue is related to MeteorComplexListView specifically, so it might be good to reduce the number of abstractions first.

Take a look at this example that does something very similar to highlight a row of listview:
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/ListViewExample.js

**Comment by sepehrooo** [comment]
@funkyeah Thanks a lot for responding.
I checked highlightRow and it will highlight the separator below the row.
I want the whole row to get an specific css styling. For example I want the touched row gets a yellow background an the text color changes to red.

Here's the app right now:
As you can see there are 2 listViews and an itemView.
I want to make the links that are touched in the list views active so that user knows which item they've selected.

![untitled](https://cloud.githubusercontent.com/assets/2351478/17073772/20b617b4-5089-11e6-89e1-438ab0d8a0fe.gif)

**Comment by funkyeah** [comment]
yes, highlight row appears not to be for highlighting the row, but rather dealing with the seperators... so seems like its terribly named to me

in the example they change the imgSource icon in this._pressRow(rowID) function so you'd kind of want to follow that bit.

Maybe modify this RNplay example https://rnplay.org/apps/xnyaYw to reflect how you are going about doing it and it will be easier to help debug. One way or another need a reproduction of the code to play with to help figure your specific issue out.

This might also help
http://stackoverflow.com/questions/34118467/react-native-change-style-of-listview-item-on-touch?rq=1

**Comment by sepehrooo** [comment]
@funkyeah Thanks a lot for these great resources.
But still I couldn't get it to work. 
I think if there's a way to trick the list view and give it an exact datasource that it already has after a row is touched it will do what I want and re renders, but the thing is I don't know how to do that in  MeteorComplexListView or even in the ListView itself.

**Comment by funkyeah** [comment]
if you make a reproduction repo that attempts to do just this in the method you described at the top I'd be happy to take a look. I'm a bit of a noob so can't promise I'll be able to get anything working either but couldn't hurt if you are stuck.

**Comment by sepehrooo** [comment]
@funkyeah Thanks a lot for helping me out with this.
I've found a solution for others having this problem.
You can give ListView or MeteorComplexListView a key prop and when that key changes, the listView will re render.
`<MeteorComplexListView 
key={this.state.itemId} 
elements={()=>{return Meteor.collection('items').find()}}
renderRow={this.renderItem.bind(this)} 
/>`
