### ISSUE TITLE
Facebook / OAuth Provider Logins?

### ISSUE THREAD

**Issue by patrickdevivo** [inProgress-team/react-native-meteor#109]
Is there an easy way to implement Meteor Accounts login with Facebook using this package?

**Comment by funkyeah** [comment]
http://lmgtfy.com/?q=meteor+react+native+facebook+oauth#

**Comment by funkyeah** [comment]
But in all seriousness I think the spencercarli repo is  the best guidance available

**Comment by JulianKingman** [comment]
If you're using exponent, it makes it even simpler. Combine with Spencer's === win
