### ISSUE TITLE
Multiple user accounts

### ISSUE THREAD

**Issue by mquandalle** [inProgress-team/react-native-meteor#111]
Hi,

I’m building a react-native application for [Wekan](https://github.com/wekan/wekan) using react-native-meteor, and so far the experience has been very pleasant with this package, so thank you for creating and maintaining it :)

On this application I’d like users to be able to register using multiple accounts (like in the Twitter application for instance), and these accounts would potentially be attached to different DDP servers (Wekan is an application you can self-host). I think this is pretty easy to implement, it’s just a matter of keeping the different identities (token_key + DDP server URL) in a list persisted using the `AsyncStorage` API, and then using `Meteor.disconnect` and `Meteor.connect` + `Meteor.loginWithPassword ` with the new credentials to switch identities.

I wonder if you’re willing to support this use case directly in this library (I can work on a PR), or if you think it should be a distinct package on top of it.

**Comment by Mokto** [comment]
Hi,

Thanks for your feedback !

I try to fit to the Meteor specs, so I think this should be a distinct package on top of it !

If you do so, please tell me so that I add your package to react-native-meteor readme ;)
