### ISSUE TITLE
Client-side method definitions

### ISSUE THREAD

**Issue by Brendtron5000** [inProgress-team/react-native-meteor#114]
Meteor recommends defining methods in client and server code to support optimistic UI updates. Does react-native-meteor have support for this, or is the only way to perform optimistic/offline updates to use insert etc. directly?

**Comment by Mokto** [comment]
I'm not sure I fully understand your question, sorry.

But react-native-meteor allows you to make optimistic insert and remove (you can't make optimistic updates yet).

**Comment by Brendtron5000** [comment]
Yes, I think doing an insert directly like so works:

`Meteor.collection('tasks').insert({text: 'something to do'});`

But if I wanted to use `Meteor.call`, I wouldn't get the optimistic updates, as I'm not able to define the methods in the client-side code in my react native app. If I am offline the call simply fails and does not update any data remotely or locally.

I tried defining my method as I usually do client-side.

```
Meteor.methods({
  'tasks.insert'(text) {
    check(text, String);
    Meteor.collection('tasks').insert({text: text});
  }
});
```

The above code gives me an error saying `Meteor.methods` is not defined.

**Comment by grsabreu** [comment]
The `Meteor.methods` can work for client-side in a Meteor browser app because the codebase can be shared across server and client.
Which isn't possible for react-native-meteor as it isn't under the Meteor program.

**Comment by Mokto** [comment]
Oh right, so the explanation is given, I'm closing this.

Thanks @grsabreu.

**Comment by grsabreu** [comment]
:+1:
