### ISSUE TITLE
Unnecessary connect() when calling Meteor.logout();

### ISSUE THREAD

**Issue by swhamilton** [inProgress-team/react-native-meteor#115]
I am using the Switch functionality as written in the example app and I noticed a quick flicker to the "loading" scene after calling Meteor.logout() before displaying the login scene.

I was able to diagnose the issue by adding a log here:
```javascript
  getMeteorData() {
    let data =  {
      loggingIn: Meteor.loggingIn(),
      user: Meteor.user(),
      userId: Meteor.userId(),
      connected: Meteor.status().connected, // would expect this to stay true after calling Meteor.logout().
    };
    console.log('connected:', data.connected); // will print false then true on logout().
    return data;
  }
```
I found out that on logout(), the Meteor.status().connected gets set to FALSE and then TRUE. This seems incorrect as the Meteor connection is not broken, only the user logged in status changes.

I did some digging and found that this connect() function gets called on logout(). 
https://github.com/inProgress-team/react-native-meteor/blob/50c75b6a9f3a38aa488d87db388fd0d043e82ecf/src/user/User.js#L28

Is there a reason for this connect() in the logout() method?

**Comment by Mokto** [comment]
This is because when I call Meteor.logout, DDP server automatically disconnects.

I don't know why and this seems untrue. Maybe this is from ddp.js ?
