### ISSUE TITLE
cannot get data on componentDidMount in 1.0.0-rc14

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#117]
here is my code:
```
  getMeteorData(){
    const handler = Meteor.subscribe('vm');
    const vms = Meteor.collection('vm').find();

    return {
      ready: handler.ready(),
      vms: vms
    }
  }

  componentDidMount(){
    const {ready, vms} = this.data;
    
    //THIS IS NEVER READY OR ALWAYS RETURN FALSE, AND NOT REACTIVELY CHANGED
    if(ready){ 
      console.log('did mount')
      console.log(vms); // <--- SO THIS ONE NEVER BEING ABLE TO BE CALLED
    }
  }
```

**Comment by Mokto** [comment]
Sure, because your handler is not ready at the time your component mounts.

You have to use componentWillReceiveProps if you want to check this.

**Comment by radiegtya** [comment]
not working too, even the console.log is not working

```
componentWillReceiveProps(){
    console.log('will receive props');
    const {ready} = this.data;
    console.log(ready);
}
```

**Comment by grsabreu** [comment]
Actually I think you should use `componentDidUpdate` instead.
The `getMeteorData` mixin doesn't make React trigger component*Props but instead it does trigger `component*Update`. If none of that works for you, you should consider using a container so you'll be able to use `component*Props`

**Comment by Mokto** [comment]
Thanks @grsabreu for the explanation. 

componentWillReceiveProps works in my case because I use createContainer.

Closing this ;)

**Comment by grsabreu** [comment]
:+1:
