### ISSUE TITLE
DDP disconnects when switching to 4g from Wifi.

### ISSUE THREAD

**Issue by donedgardo** [inProgress-team/react-native-meteor#119]
### Expected behavior
When you change your cellphones wireless connection to its Data network (LTE, 4G, etc.),
it should disconnect for a brief time and reconnect to the DDP.

### Actual behavior
When changing from wifi to Cellphone data network it disconnects from DDP and hangs.

Video demonstrating bug:

Loading app from Ad Hoc server directly from my phone (Xcode is not serving my app).

<iframe src="https://player.vimeo.com/video/178938913" width="640" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/178938913">rnmeteorddperror</a> from <a href="https://vimeo.com/user53860032">Edgardo Carreras</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

### Steps to reproduce behavior 
Project built from [react-native-meteor-boilerplate](https://github.com/spencercarli/react-native-meteor-boilerplate).

Ddp connection config
```javascript
// Android and Devices(Ios and Android)
// let METEOR_URL = 'ws://192.168.1.2:3000/websocket';


// Production Server
let METEOR_URL = 'ws://piso13.skyrocketdev.com/websocket';

if (process.env.NODE_ENV === 'production') {
  METEOR_URL = 'ws://piso13.skyrocketdev.com/websocket'; // your production server url
}


const config = {
  env: process.env.NODE_ENV,
  METEOR_URL,
};

export default config;
```

This is how use this config: 
```javascript
import React from 'react';
import Meteor, { createContainer } from 'react-native-meteor';

import { Scene, Router } from 'react-native-router-flux';
import { connect, Provider } from 'react-redux';
import Store from './store/store';

import NewsWebView from './routes/NewsWebView';
import Profile from './routes/Profile';
import LoggedOut from './layouts/LoggedOut';
import LoggedIn from './layouts/LoggedIn';
import Loading from './components/Loading';
import WebViewNavBar from './components/WebViewNavBar';
import config from './config';


const options = {
  autoConnect: true,
  autoReconnect: true,
};
Meteor.connect(config.METEOR_URL, options);

const RNApp = (props) => {
  const { status, user, loggingIn, selectedNews } = props;
  console.log(selectedNews);

  if (status.connected === false || loggingIn) {
    return <Loading />;
  } else {
    return (
      <Provider store={Store}>
        <Router>
          <Scene key="newsList" component={LoggedIn} title="News List" initial={true}/>
          <Scene key="news" component={NewsWebView} navBar={WebViewNavBar}/>
          <Scene key="signIn" component={LoggedOut} title="Sign In"/>
          <Scene key="profile" component={Profile} title="Profile"/>
        </Router>
      </Provider>
   );
  }
};

RNApp.propTypes = {
  status: React.PropTypes.object,
  user: React.PropTypes.object,
  loggingIn: React.PropTypes.bool,
};

export default createContainer(() => {
  return {
    status: Meteor.status(),
    user: Meteor.user(),
    loggingIn: Meteor.loggingIn(),
  };
}, RNApp);
```

**Comment by donedgardo** [comment]
Apparently its only an issue when using LTE from providers like NET10. Not sure why, maybe low quality connection.

**Comment by elie222** [comment]
Are you using SSL? I know with Meteor websites that don't use SSL, some countries / operators won't allow the websocket connection.

**Comment by donedgardo** [comment]
Thanks @elie222 that might be the issue. Setting up ssl.

**Comment by donedgardo** [comment]
Thank you that was it.

**Comment by elie222** [comment]
Great. Happy to hear it helped.
