### ISSUE TITLE
Example of composite collection use

### ISSUE THREAD

**Issue by c316** [inProgress-team/react-native-meteor#120]
It would be great to see an example of using two or more collections in a MeteorListView. The process of subscribing to and using more than one collection is documented well in Meteor, but I can't wrap my head around how this would be done with react-native-meteor. 

Thanks

**Comment by andrewnoh** [comment]
Yes, I am also struggling with this. 

For example, I have 2 Collections: `Messages` and `Conversations`

A `Message` has a `conversationId` that ties it to the `_id` of a `Conversation`. 

I would like to somehow get the most recent `Message` of a `Conversation` and make this available when I do <MeteorListView collection="conversations">` -> `renderRow(conversation) return (<Text>{conversation.lastMessage}</Text>);` or any other way I can get this data when I'm rendering the `Conversation`. 

https://github.com/inProgress-team/react-native-meteor#meteorcomplexlistview-component this looks like it might be what I need? But the example is a bit too, so I'm not able to figure out. 

Any guidance would be sincerely appreciated.

**Comment by fermuch** [comment]
```
<MeteorComplexListView
  elements={()=>{
    return Meteor.collection('Conversation').find().map((conv) => {
      const lastMsg = Meteor.collection('Message').findOne({conversationId: conv._id}, {sort: {createdAt: -1}});
     return {
       ...conv,
       lastMsg
     };
    })
  }}
  renderRow={this.renderItem}
/>
```

In this example, `renderItem` is going to receive an object with all the items from `Conversation` plus a `lastMsg` item containing the last `Message`.

**Comment by andrewnoh** [comment]
Thank you so much @fermuch ! I was stuck all day on this. Can you clarify how the publications/subscriptions would need to look? Do I need to do:

```
export default createContainer(params=>{
    const conversationsHandle = Meteor.subscribe('conversationsPublication');
    const messagesHandle = Meteor.subscribe('messagesPublication');


    return {
        conversationsReady: conversationsHandle.ready(),
        messagesReady: messagesHandle.ready()
    };
}, Inbox)
```

Where `conversationsPublication` is all of the conversations for the current user, and `messages` would be all of the messages that involve the user (seems like a lot)?
