### ISSUE TITLE
Disconnected Updates

### ISSUE THREAD

**Issue by darrenfurr** [inProgress-team/react-native-meteor#121]
Since the .update() method does not work disconnected...
How are people handling disconnected updates?

The only thing I can come up with is:  if disconnected - perform a .remove() & .insert(). Although it would create a new _id, seems negligible for disconnected use & not having to write my own sync.

**Comment by balibou** [comment]
I am looking to make the update work too but I don't know how to do that ... my repo is here: https://github.com/balibou/meteorReactNativeCRUD.
When I do an update on the RNApp, I have to make a refresh on the MeteorApp // When I do an update on the MeteorApp, I have to make a refresh on the RNApp ...
