### ISSUE TITLE
Example of ReactiveDict use?

### ISSUE THREAD

**Issue by andrewnoh** [inProgress-team/react-native-meteor#122]
Thanks!

**Comment by patrickdevivo** [comment]
+1

**Comment by Mokto** [comment]
See here :

https://github.com/inProgress-team/react-native-mantra-boilerplate/blob/master/src/client/configs/context.js

https://github.com/inProgress-team/react-native-mantra-boilerplate/blob/master/src/client/modules/user/containers/login.js
