### ISSUE TITLE
Is there a way to fix this update behavior ?

### ISSUE THREAD

**Issue by balibou** [inProgress-team/react-native-meteor#123]
Hello, 

First, awesome repo :)

I am looking to make the update work too but I don't know how to do that ... my repo is here: https://github.com/balibou/meteorReactNativeCRUD.

When I do an update on the RNApp, I have to make a refresh on the MeteorApp // When I do an update on the MeteorApp, I have to make a refresh on the RNApp ...

**Comment by grsabreu** [comment]
Hi @balibou, I can see here https://github.com/balibou/meteorReactNativeCRUD/blob/master/RNApp/package.json#L55 that you are using an old version on the package. Do you still having this problem with the latest version? Let me know.

**Comment by noris666** [comment]
@grsabreu i think problem not in version. 
I always use update by Meteor methods. Because in my opinion it is better way.
---
@balibou your problem solved now ? can we close issue ?
