### ISSUE TITLE
Getting disconnected from DDP server when trying to ToastAndroid.show

### ISSUE THREAD

**Issue by you-fail-me** [inProgress-team/react-native-meteor#124]
Every time I'm trying to show ToastAndroid app gets disconnected from DDP server and reconnects in a few seconds. The same thing occurs when I'm trying to use https://github.com/KBLNY/react-native-message-bar Have anybody had such issue? Could anybody share any ideas, what could be the reason and what could be a possible fix?

**Comment by Mokto** [comment]
Sorry I have no idea, but this is not related to react-native-meteor.
