### ISSUE TITLE
Upload files from React Native to Meteor ?

### ISSUE THREAD

**Issue by noris666** [inProgress-team/react-native-meteor#126]
Hello ! 
What method i can you use for upload image or video files into backend ?
What practices are best suited for working with files between RN and Meteor ?

Thx.

**Comment by Mokto** [comment]
This project includes CollectionFS, which is deprecated.

I think Meteor-Files is recommended, but there is no implementation of it in this project.

**Comment by dr-dimitru** [comment]
Will this work - https://github.com/VeliovGroup/Meteor-Files/wiki/React-Example?

**Comment by giovapanasiti** [comment]
No. Did you find anything? I kinda have the same problem

**Comment by dr-dimitru** [comment]
@giovapanasiti 

Here is threads where developers are using Meteor-Files with react native:
 - Using HTTP upload: https://github.com/VeliovGroup/Meteor-Files/issues/430
 - Using POST HTTP upload: https://github.com/VeliovGroup/Meteor-Files/issues/271
 - https://github.com/VeliovGroup/Meteor-Files/issues/95
 - https://github.com/VeliovGroup/Meteor-Files/issues/74

Let me know if it is useful for you
