### ISSUE TITLE
How to keep Meteor state in redux store?

### ISSUE THREAD

**Issue by swhamilton** [inProgress-team/react-native-meteor#127]
Is it possible to store the meteor state (user, loggingIn, status) in a redux store using react-native-meteor?

I see two solutions:
1. Wrap a meteor container with a redux store container (Redux parent, meteor child)
2. Wrap a redux container with a meteor container. (Meteor parent, redux child)

Is there a correct way to do this?

This has some good insight into the problem but I was unable to get the store event correctly connected.
https://forums.meteor.com/t/solved-meteor-1-3s-createcontainer-and-redux-dispatch-event-handlers-etc/20092/9

Here's another approach that updates the store with a dispatch.
https://gist.github.com/spencercarli/8a0eea08a218cc16a35938fd3a95fc45#file-meteorconnect-js

Here's my attempt that wraps Meteor outside the store, but I don't know how to access the Meteor prop data.

```javascript
// Bootstrap the app
const App = (props) => {
	const { status, user, loggingIn } = props;
	return (
		<Provider store={store}>
			<RootContainer {...props}/>
		</Provider>
	);
};

// Redux (inner) container
const RootContainer = connect(state => ({
    counterState: state.counter,
    appState: state.app,
	userStorageState: state.userStorage
  }),
  (dispatch) => ({
    appActions: bindActionCreators(appActions, dispatch),
    userStorageActions: bindActionCreators(userStorageActions, dispatch),
    counterActions: bindActionCreators(counterActions, dispatch)
  })
)(MyRootComponent);

// Outer container, passed to index.ios.js/index.android.js
export default createContainer(() => {
	return {
		status: Meteor.status(),
		user: Meteor.user(),
		loggingIn: Meteor.loggingIn(),
	};
}, App);
```

Any help or pointers would be great!

**Comment by seanowenhayes** [comment]
I usually wrap the meteor container in the redux connect so that I can pass search parameters from the view via the redux store into meteor to query the domain data. My current solution is so inelegant I am embarrassed to share. I would love to find an elegant solution.

**Comment by Mokto** [comment]
The elegant way I use is https://github.com/kadirahq/react-komposer

**Comment by artem-russkikh** [comment]
@Mokto can you show an example?

**Comment by Mokto** [comment]
See here : https://github.com/inProgress-team/react-native-mantra-boilerplate

**Comment by smooJitter** [comment]
@artem-russkikh  Note: the above approach is based on the Mantra application framework.  You'll need to become somewhat familiar with Mantra to appreciate the value of react-kompser.
