### ISSUE TITLE
Q: Is there a way to change subscription dynamically?

### ISSUE THREAD

**Issue by donedgardo** [inProgress-team/react-native-meteor#128]
Lets say I have a search option in my react native app, and i want to send that search as a second parameter in my subscription to my server for server pagination.
```Meteor.subscribe('filteredListFromServer', searchParameter)```
Is there any way i can reactively set my subscription with those search parameters inside a createContainer function?

**Comment by noris666** [comment]
Hello @donedgardo ! 
You can use state params.

My working example for searching friends:
https://gist.github.com/noris666/216db4af4338dea6cf4fe946fcf7a391

**Comment by Mokto** [comment]
Thanks @noris666.

**Comment by martin-eq** [comment]
@noris666 is there a way to access the component's state using `createContainer` instead of `getMeteorData`?

**Comment by noris666** [comment]
@martin-eq i think yes, in next days i will rewrite this part of that code and then i tell to you about my results. Because i also now move from getMeteorData to createContainer.

**Comment by JulianKingman** [comment]
@noris666 did you ever do this? I am trying to do it like this, but I don't think it's working:
````javascript
export default createContainer((props) => {
  const params = props.params;
  const taskSubscription = Meteor.subscribe('getTasks', params, {});
  return {
    tasksReady: taskSubscription,
    tasks: Meteor.collection('tasks').find({}),
  };
}, TaskList);
````
It seems to invalidate the subscription or something.

**Comment by JulianKingman** [comment]
Question: for this to work, doesn't the subscription need to reactively depend on the parameters?

**Comment by imspikey** [comment]
any update on this situation?!
