### ISSUE TITLE
Using ListView DataSource Best Practices with react-native-meteor 1.0.0-beta2

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#13]
Am I doing it right?
Because currently I can't set the ds within state, I can only set it on render, so I don't use state like RN ds usually used.

here is my code, is this correct way to implement:
```javascript
@connectMeteor
class MeteorRN extends Component {

  constructor(){
    super();

    this.ds = new ListView.DataSource({
      rowHasChanged: (row1, row2) => !_.isEqual(row1, row2),
    });
  }

  startMeteorSubscriptions() {
    Meteor.subscribe('channels');
  }

  getMeteorData() {
    //I can't set state here to update DS row like RN best practice, because data here is not valid
     return {
       channels: Meteor.collection('channels').find()
     }
  }

  _renderRow(rowData){
      return (
        <TouchableHighlight style={styles.row}  underlayColor='#c8c7cc'>
          <Text>{rowData.name}</Text>
        </TouchableHighlight>
      );
  }

  render(){
    const {channels} = this.data;

    return (
        <View style={styles.container}>
          <ListView
            dataSource={this.ds.cloneWithRows(channels)}
            renderRow={this._renderRow}
            style={styles.listView}
          />
        </View>
    )
  }

}
```

**Comment by Mokto** [comment]
Your solution is fine, but not perfect in my opinion.

Because you cloneWithRows at each render. In your case it is fine because your class rerender only if channels change, but I might add a listener for data change in startMeteorSubscriptions.

I have to think about it.

What do you think ?

**Comment by radiegtya** [comment]
I think the best solution is like this:

```javascript
startMeteorSubscriptions(){
  Meteor.subscribe('channels', ()=>{
     //you can set any state here 
     this.setState({
        channels: Meteor.collection('channels').find()
     });
  }); //provide a callback
}

```

is that possible? so the data will wait until subscriptions really ready and not re-render every time.

**Comment by Mokto** [comment]
Yes it is ok but :

```javascript
this.setState({
     ds: this.state.ds.cloneWithRows(Meteor.collection('channels').find())
});
```

And your subscriptions can be made in another components (at top level for example) so it might not be enough.

**Comment by radiegtya** [comment]
Ya, subscriptions should be able to be called anywhere. ex: constructor, componentWillMount, componentDidMount etc. And it should have callback to know whether its ready or not. Then inside it we can have Meteor.collection method. But Meteor.collection should be able to be get from another component too. Is that possible?

**Comment by radiegtya** [comment]
Any update to this?

**Comment by Mokto** [comment]
I am more and more thinking about creating a MeteorListView component for this usage.

It could be nice. I will let you know when that happens ;) But I have to think a bit more about this.

**Comment by radiegtya** [comment]
wow it will be amazing, hopefully it also have cached data on it too like miniMongo does. :+1: 
but that's not very important for now, let's stick to make the MeteorListView stable first.

**Comment by Mokto** [comment]
Done :) 

1.0.0-beta8

**Comment by radiegtya** [comment]
@Mokto : I think you have wrong implementation at Readme for MeteorListView

```javascript
renderRow(todo) {   //YOU HAVE renderRow here
    return (
      <Text>{todo.title}</Text>
    );
  }
  render() {
    const { settings } = this.data;

    <View>
      <Text>{settings.title}</Text>
        <MeteorListView
          collection="todos"
          selector={{done: true}}
          options={{sort: {createdAt: -1}}}
          renderItem={this.renderItem}              //BUT YOU ARE ASSIGNING renderItem here
        />
    </View>

  }
```

which one is correct? Sorry I am not yet able to test it, forget that today is holiday :family:

**Comment by Mokto** [comment]
Take your time test, enjoy your family ;)

Thanks, I just updated readme.

**Comment by radiegtya** [comment]
Good job, the other things which still disturb me is how to query with related models in MeteorListView. If using regular ListView, I can do something like this, for example user belongsTo channels.

```javascript
getMeteorData() {
    var channels = Meteor.collection('channels').find();
    var Users = Meteor.collection('users');
    var i = 0;
    channels.forEach((channel)=>{
          //get related user by channel.userId
          var user = Users.findOne(channel.userId);
          
         //then pass the user data to channels array
         channels[i].user = user;
         i++; 
    });   

     return {
       channels: channels
     }
  }
```

but when using MeteorListView, I think that I can't doing that, because of it's only able to pass query data

```javascript
<MeteorListView
          collection="channels" //only channels collection are passed, and I can't modify this 
          selector={{done: true}}  //selector is already good
          options={{sort: {createdAt: -1}}} //options is already good
          renderItem={this.renderItem}       //and it's impossible to modify array here
        />
```

How do you think @Mokto ?

Thanks :yum:

**Comment by Mokto** [comment]
Mhhh,

I think the better way to do this is :

```javascript
export default class Channels extends Component {
  renderItem(channel) {
    return (
      <UserItem id={channel.userId} />
    );
  }
  render() {
    return (
      <MeteorListView
        collection="channels"
        renderItem={this.renderItem}
      />
    );
  }
}


@connectMeteor
class UserItem extends Component {
  getMeteorData() {
    const { id } = this.props;
    return {
      user: Meteor.collection('users').findOne(id)
    };
  }
  render() {
    const { user } = this.props;

    return (
      <Text>{user && user.username}</Text>
    )
  }
}
```

I have not tested this code but it should work ;)

**Comment by radiegtya** [comment]
yeah that should do the trick, but I think that's too overbloated. But it's ok for now. Thanks
