### ISSUE TITLE
Access props inside createContainer

### ISSUE THREAD

**Issue by java99** [inProgress-team/react-native-meteor#132]
I tried to access some props I pass to my container to customize the meteor search - sample as in 

https://github.com/inProgress-team/react-native-meteor#example-usage

I get the error

**undefined is not an object (evaluating '_this.props.myProps')**

so how can I make props available for createContainer method?

**Comment by seanowenhayes** [comment]
The props are passed in the parameter called params in the example. Below is a modified example making it more explicit.
```js
export default createContainer(props=>{
  let {status} = props;
  return {
    pendingOrders: Meteor.collection('orders').find({status}),
  };
}, Orders);
```

**Comment by java99** [comment]
Thanks. Figured it out!
