### ISSUE TITLE
Meteor.collection('users').find() or findOne() return null object

### ISSUE THREAD

**Issue by 2ducanhpham** [inProgress-team/react-native-meteor#139]
please help me?

**Comment by suryaiiit** [comment]
It should be Meteor.users.find() or Meteor.users.findOne()

Refer: https://guide.meteor.com/accounts.html#meteor-users-collection

**Comment by noris666** [comment]
Are you have subscribition with users data ?

**Comment by noris666** [comment]
@suryaiiit this is not correct, because here with this package you need to use the Meteor.collection('CollectionNameHere').find or findOne method. 
Accounts saved in users collection by default.

**Comment by 2ducanhpham** [comment]
hm. i try with other collection ,but return NULL.
I connected and login with password.

**Comment by noris666** [comment]
@2ducanhpham you can show you server side code ? 
because login use method via ddp, this is not what you will said.

To check you problem, create gist of:
1. Server side code with publish your data
2. Client side (react native)

**Comment by 2ducanhpham** [comment]
Sever side nothing.
@noris666 . you can wirte example between server side and client side for Meteor.collection.
My English is not good.

**Comment by guilhermedecampo** [comment]
@2ducanhpham you can take a look on the example https://github.com/inProgress-team/react-native-meteor/tree/master/example

Make sure that you run the meteor app along with the react-native app.

**Comment by noris666** [comment]
Hey @2ducanhpham ! 

@guilhermedecampo told good things for you. 
Have you tried the examples for better understanding?

Your problem is solved ? Can i close this issue ?

**Comment by 2ducanhpham** [comment]
thanks @guilhermedecampo , @noris666 . Its working
