### ISSUE TITLE
export hashPassword

### ISSUE THREAD

**Issue by elie222** [inProgress-team/react-native-meteor#140]
If this package could export hashPassword too that would be nice:
https://github.com/inProgress-team/react-native-meteor/blob/e4f9bdc96b154150f53fdfb8cf44605a6a618b97/lib/utils.js

If you use `accounts-core` in your project you need it for signup as here:
https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L195-L209

**Comment by Mokto** [comment]
import { hashPassword } from 'react-native-meteor/lib/utils';

**Comment by elie222** [comment]
Thanks!
