### ISSUE TITLE
Small error in the docs

### ISSUE THREAD

**Issue by kevando** [inProgress-team/react-native-meteor#141]
In the connectMeteor example, getMeteorData() sets data to `this.data` not `this.props` so this line should be change:

`const { pendingOrders } = this.props;`

to

`const { pendingOrders } = this.data;`

**Comment by kevando** [comment]
Not a big deal, I know, but this caused me some grief until I figured it out. Love the package! thanks again

**Comment by grsabreu** [comment]
Thanks for pointing this out, @kevando! Fixed.
