### ISSUE TITLE
How to completely clear minimongo

### ISSUE THREAD

**Issue by jtremback** [inProgress-team/react-native-meteor#142]
I am seeing a problem where items belonging to one user will be shown to another user who logs into the app after the first user logs out (in addition to the second user's own items).

Viewing `reactNativeMeteor.getData().db` confirms that the items from the previous user are still in minimongo. I have tried running `reactNativeMeteor.getData().db = new minimongo()`  to replace the entire minimongo, but that seems to be breaking other things, namely causing no items to show up at all.

Is there a recommended way to completely clear minimongo?

**Comment by noris666** [comment]
@jtremback 
I dont have this problems, what version of package you use ? 

Show your version of react-native-meteor package ?
If your version not 1.0.1, you need to try:

`npm install react-native-meteor@latest --save`

**Comment by noris666** [comment]
@jtremback you solve your problem ? can i close issue ?

**Comment by Mokto** [comment]
I think that after 5 days of inactivity we can close issues.
