### ISSUE TITLE
Provide a Redux API

### ISSUE THREAD

**Issue by grsabreu** [inProgress-team/react-native-meteor#147]
My thoughts in this that would make it worth writing such an API is that working with Redux makes debugging much easier and also would make possible to integrate [redux-storage](https://www.npmjs.com/package/redux-storage) for offline data in the current stack.

For the API usage I think a HoC would be the better approach and that component would provide a `meteor` prop that would allow the user to invoke subscriptions, calls and database state. Why a HoC? Because for `subscriptions` and other reactive data we need to listen hook up a handler to `unmount` so we can stop the Tracker computation when it isn't needed anymore.

The usage I have in mind in code:

``` js
import { connectMeteorRedux } from 'react-native-meteor'

export default connectMeteorRedux(
 function mapReactiveDataToProps(meteor){
  meteor.subscribe('todos', {...}) // dispatches {action: 'meteor/subscribe', args: ...}
  return {
    todos: meteor.collection('todos').find(),
    addTodo: meteor.call('todos/add') // returns a bound function that whenever gets called dispatch {action: 'meteor/call', args: ...},
  }
 }
)

// ...
import TodosContainer from '...'

function Todos({ todos, addTodo }){
 const ds = ...todos...
 return (
   <View>
    <SomeForm onSubmit={newTodo => addTodo(newTodo)} />
    <ListView
      dataSource={ds}
      renderItem={() => ...}
    ><ListView>
   </View>
 )
}

export default TodosContainer(Todos)
```

I'm willing to create a PR to start this work but I want to know your thoughts and opinions because I think the idea can get better.

@Mokto @noris666

**Comment by noris666** [comment]
Moved: https://github.com/inProgress-team/react-native-meteor/issues/154
