### ISSUE TITLE
callLoginMethod equivalent

### ISSUE THREAD

**Issue by MinhCNguyen** [inProgress-team/react-native-meteor#152]
With several login handlers registered, I want to be able to use an equivalent of Accounts.callLoginMethod ; however, we currently only support loginWithPassword

**Comment by noris666** [comment]
Hello @MinhCNguyen !
We already support this functional ! 
You can use login by username and email with [loginWithPassword](https://github.com/inProgress-team/react-native-meteor/blob/master/src/user/User.js#L39-L44)

**Comment by MinhCNguyen** [comment]
@noris666 , it seems like that method doesn't go through the login handlers. So I usually get 'the user doesn't have password' even when I have registered a handler to send the user name and password to external service. callLoginMethod does the job but is not available on react-native-meteor

**Comment by Mokto** [comment]
You could use _login method.

https://github.com/inProgress-team/react-native-meteor/blob/b5013301924cb9b33d72796a5038b2c635b1b176/src/user/User.js#L69

Not documented but... ;)

**Comment by MinhCNguyen** [comment]
@Mokto  perfect, thank you!

**Comment by liberatomota-itcenter** [comment]
Hello,
It would be great if the method was supported
