### ISSUE TITLE
Meteor streamer support ?

### ISSUE THREAD

**Issue by Micjoyce** [inProgress-team/react-native-meteor#156]
Is it possible to support meteor-streamer [https://github.com/RocketChat/meteor-streamer](https://github.com/RocketChat/meteor-streamer)

**Comment by wandonye** [comment]
@Micjoyce I'm using RocketChat and react-native meteor too. Were you able to subscribe to the collections published on RocketChat server? I encountered something weird: Every time I change the collection, my RN will get an update. But the update I get is always an empty array. Will really appreciate it if you can give some suggestion.

**Comment by noris666** [comment]
@Micjoyce i think you can extend react-native-meteor package.
In my opinion it is not difficult to implement that, look to package client source code:
https://github.com/RocketChat/meteor-streamer/blob/master/packages/rocketchat-streamer/client/client.js

**Comment by Micjoyce** [comment]
@wandonye  I create a example [https://github.com/Micjoyce/react-native-meteor-streamer-example](https://github.com/Micjoyce/react-native-meteor-streamer-example) 
If have bug, please tell me .
TKS!

**Comment by noris666** [comment]
@Micjoyce sorry for the late reply. Which bug ? Can you explain ?
