### ISSUE TITLE
Updating npm package

### ISSUE THREAD

**Issue by elie222** [inProgress-team/react-native-meteor#159]
The last update to the package number was done a month ago, but a bunch of commits have happened since then.
Would it be possible to publish the updated package to npm and bump to 1.0.2.

**Comment by noris666** [comment]
@elie222 updated :-) thx 4 your feedback ! (https://github.com/inProgress-team/react-native-meteor/commit/662cbbe16e76abb1e1aedf879c0ec3ce55168f91)

**Comment by elie222** [comment]
Thanks!

**Comment by elie222** [comment]
The npm package hasn't been updated yet:
https://www.npmjs.com/package/react-native-meteor
(Last update a month ago and version 1.0.1)

**Comment by noris666** [comment]
@Mokto can you help to update version ?

**Comment by elie222** [comment]
theo-mathieu published a month ago according to RN. Is that @Mokto?

**Comment by noris666** [comment]
@elie222 yes i only can make changes in repo not in npm package. Need wait @Mokto.

**Comment by Mokto** [comment]
I just updated the npm package to 1.0.2.

;)

**Comment by noris666** [comment]
@elie222 all good 💯  I already update package in my application. Try again please.

```
$ npm i react-native-meteor@latest
geomem@0.0.1 /Volumes/NORISCLOUD/Development/ReactNative/...
└── react-native-meteor@1.0.2 
```

**Comment by elie222** [comment]
cool. that works. thanks `--save`
