### ISSUE TITLE
Connection status unreliable

### ISSUE THREAD

**Issue by tvogels** [inProgress-team/react-native-meteor#16]
This is a great library. I especially like the built in reconnect-mechanism. It works well if I reboot my meteor server, but if I set the phone to flight mode, the status remains 'connected' an no automatic reconnect happens. Is this a known problem? It is probably a problem with ddp.js ...

Similarly, changing changing from Wifi to 4G connection drops the connection without any notice.

**Comment by radiegtya** [comment]
This is happened to any ddp js plugin such as asteroid, ddp-client etc. This is make any mobile apps hang sometime when changing from 3g to 4g or 4g to wifi or 4g to plane mode. I know because I am already make a production apps with ionic + ddp and also rn + ddp.

**Comment by Mokto** [comment]
I'm about to to something about it thanks to [NetInfo](https://facebook.github.io/react-native/docs/netinfo.html#content) ;)

**Comment by radiegtya** [comment]
will wait for this too. This plugin will be amazing!

**Comment by Mokto** [comment]
Is this still an issue ?

I do not have 3G/4G on my tablets, but when I disconnect manually my WIFI, DDP disconnects, and when I reconnect my WIFI, DDP reconnects.

My last commits might have resolve this (update ddp.js to 2.1.0). Please tell me ;)

**Comment by tvogels** [comment]
1.0.0-beta6 definitely changed this. It seems that I cannot make the connection break anymore. Meteor.status().status is correctly changed to 'disconnected' when the network changes, and it is reestablished automatically. It does, however, take very long to reconnect. `connection.connected` stays false for up to about 10 seconds. 

Before, I tried this approach with *NetInfo*:

```js
  constructor() {
    ...
    NetInfo.isConnected.addEventListener(
      'change',
      this.changeNetInfo.bind(this)
    );
  }
  ...
  changeNetInfo(isConnected) {
    if (isConnected)
      Meteor.connect(METEOR_URL);
  }
```

This seemed to reconnect quickly (without noticeable time disconnected), but subscriptions somehow also need to be refreshed, I think.

**Comment by radiegtya** [comment]
On Ionic I can simply rerender all components with refreshing the page by force, when DDP is offline. Because it will make it hang about 10 sec when dc in ionic if I am not doing that (don't know on react).

How did it happen on react-native @tvogels ? Is it hang on dc or it just can't get data or completely broken?

**Comment by Mokto** [comment]
I think I can close this issue now.

Fast reconnection when network state changes has been added in 1.0.0-beta7.

Thanks @tvogels !

**Comment by tvogels** [comment]
@radiegtya I make my app show a loading screen when the reactive variable Meteor.status().connected == false. This loading screen just showed for 10 seconds when I switch network. But now it seems to work well, indeed. Thanks a lot, @Mokto!

**Comment by radiegtya** [comment]
this is amazing! thanks @tvogels @Mokto

**Comment by radiegtya** [comment]
@Mokto : btw subscriptions still not reconnected automatically, and it make my data cannot displayed when switching 3g/4g to wifi

**Comment by radiegtya** [comment]
Any update about this @Mokto

**Comment by Mokto** [comment]
I'm reopening this and will think about it when I am more available  ;)

**Comment by radiegtya** [comment]
@Mokto : thanks, will wait for this before updating my production apps. :+1:

**Comment by Mokto** [comment]
Oh then I will be looking into this very fast !

**Comment by radiegtya** [comment]
btw this can be hacked by Meteor.ddp.on('connect') function then set a state to trigger subscriptions. but those thing is not working too. Dunno why or I should importing another module. 

An auto subscribe when reconnect will be better though.

Thanks a lot @Mokto

**Comment by Mokto** [comment]
Should be ok now ;)

1.0.0-beta12.

Feel free to reopen if any issue !

**Comment by radiegtya** [comment]
how to use this? I am console log something in "startMeteorSubscriptions" method and nothing is printed while reconnecting?

**Comment by radiegtya** [comment]
Update: dunno why but it just work.. I'll update the status when I found any more bug. Thanks a lot @Mokto

**Comment by Mokto** [comment]
Nothing to do indeed, I restart every subscription when it is reconnected to DDP.

**Comment by donedgardo** [comment]
I'm also having this issue. My react-native app disconnects and hangs by switching networks 
( Wifi -> 4G ).

Mind you my app is already deployed in Ad Hoc Deployment it shouldn't need to stay in the same network. My meteor.connect is pointing to my production servers too.
