### ISSUE TITLE
authen connection????

### ISSUE THREAD

**Issue by tanmynguyen** [inProgress-team/react-native-meteor#160]
I use url = **ws://reqes:samcard2016@example.com:3000/websocket** but not connect to server meteor. But if i use **ws://example.com:3000/websocket** then it connected!!!
help me??

**Comment by grsabreu** [comment]
have you tried `ws://reqes:samcard2016@example.com/websocket`?

**Comment by tanmynguyen** [comment]
@grsabreu thanks you!! But i try it and not work!! :(

**Comment by tanmynguyen** [comment]
@noris666 Hi!!
Because, I use authorization for frontend, who's that avoid can view web of me when i developing. But ws not connect to meteor server!! :(
