### ISSUE TITLE
[Question] React Native and Meteor + Push notification

### ISSUE THREAD

**Issue by cyclops24** [inProgress-team/react-native-meteor#168]
Hi guys,
Later in cordova we have riax:push module and that module handle push notification in GCM and ... in both client and server. Now when we use `react-native-meteor` and `react-native` how we can implement push notification functionality.
Please guide me.

**Comment by noris666** [comment]
Hello ! I'm use onesignal to send push notifications, it is simple way to get that functionality.

**Comment by cyclops24** [comment]
@noris666 do you have any idea about integrate this with Meteor?
For example how we can send notification to specific userId?

**Comment by noris666** [comment]
@cyclops24 of course you can do logic what you will need.
With Meteor you can you that package: https://github.com/Astrocoders/meteor-one-signal
I combine Meteor package with https://github.com/geektimecoil/react-native-onesignal and this works as well.
If you have any questions @spencercarli wrote good articles about that.

https://medium.com/differential/react-native-push-notifications-with-onesignal-9db6a7d75e1e#.3p1nvj970
https://medium.com/differential/handling-remote-push-notifications-from-onesignal-in-react-native-5897804b0015#.882wvrl9z

**Comment by cyclops24** [comment]
@noris666 Thanks for your rapid reply and awesome links.
My last question is in React-Native side how we can set UserId as deviceId I see in [react-native-onesignal-readme](https://github.com/geektimecoil/react-native-onesignal#getting-player-id-and-push-token) that pass `device.userId` and `device.pushToken` to `onIdsAvailable` callback. How we can register device to OneSignal with Meteor.UserId?

---
I also open new thread in meteor forum to talk about this in detail. I'm so glad if you join me there too:
https://forums.meteor.com/t/needs-help-to-integrate-onesignal-with-meteor-js/32172

**Comment by spencercarli** [comment]
Just left an answer on the meteor forum post 😄

**Comment by cyclops24** [comment]
Thanks @spencercarli ,
I can implement this man and seems OneSignal works well.
Aaaaaaaaaaaaaaaaaaaand Happy New Year Guys. 🎄 

**/CC:** @noris666 , @FaridSafi , @grsabreu , @josephdburdick
