### ISSUE TITLE
Galaxy websocket address/port

### ISSUE THREAD

**Issue by mikepaszkiewicz** [inProgress-team/react-native-meteor#171]
I'm attempting to stage a react-native client hooked up to my galaxy instance, but all examples I'm finding are examples for local development purposes.
```
Meteor.connect('ws://192.168.X.X:3000/websocket');//do this only once
```
I assume I can swap out the IP address with the url, but what do I swap in for port on Galaxy?

**Comment by simonbelanger** [comment]
I don't have to specify a port to open websockets with applications hosted on Galaxy, something like `wss://mydomain.com/websocket` works perfectly fine.

**Comment by noris666** [comment]
@mikepaszkiewicz problem solved ?

**Comment by mikepaszkiewicz** [comment]
i've been learning RN for a side project and haven't had the chance, will reopen if this doesn't work for me. thanks!
