### ISSUE TITLE
[Request] Please add a gitter chat

### ISSUE THREAD

**Issue by cyclops24** [inProgress-team/react-native-meteor#173]
Hi @Mokto ,
I think a simple gitter chat room has very useful for some knowledge sharing in this package community.
It's a suggestion man. Think about it. 😉

**Comment by noris666** [comment]
@cyclops24 https://gitter.im/react-native-meteor/Lobby you already invited.

**Comment by cyclops24** [comment]
Thanks @noris666 ,
Your are awesome man.
I also suggest add this to repo ReadMe.md so others can also join there. 😉

**Comment by noris666** [comment]
@cyclops24 readme updated.

**Comment by cyclops24** [comment]
Thanks brow, you are awesome. 😉
