### ISSUE TITLE
Subscriptions Ready can't handle a field with Long text 

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#174]
For example 

```

getMeteorData(){
 const handler = Meteor.subscribe('messages');

  return {
     ready: handler.ready()
  }
}

render(){
  MeteorListView....
}
```

and field message.text with very long text cannot shown on limit 20. but it can be shown on limit 10

**Comment by noris666** [comment]
@radiegtya please write more info please, because your example so abstract.
