### ISSUE TITLE
Helper for Meteor-CollectionFS

### ISSUE THREAD

**Issue by Mokto** [inProgress-team/react-native-meteor#18]
https://github.com/CollectionFS/Meteor-CollectionFS

Uses something like this :
`meteor.getUrl()+'/cfs/files/imagesFiles/'+imageFile.$value._id+'?token='+btoa(JSON.stringify({authToken: token}))`

**Comment by radiegtya** [comment]
Wow, you are really on this. You rock man! 
I think this can be the future Native development based on Meteor + RN

**Comment by Mokto** [comment]
Available in 1.0.0-beta15.
