### ISSUE TITLE
Not connection https://mydomain.com:3000/

### ISSUE THREAD

**Issue by tanmynguyen** [inProgress-team/react-native-meteor#182]
Hi guys!!
I can't connect to server with domain https://mydomain.com:3000/
`import { Platform } from 'react-native';

let IPV4 = 'https://mydomain.com:3000'; // meteor in server
export default {
    url: 'wss://'+IPV4+'/websocket'
}`
help me!!!

**Comment by noris666** [comment]
Correct use without https://

**Comment by tanmynguyen** [comment]
If not use https://, secure guaranteed???

**Comment by noris666** [comment]
@tanmynguyen if you use wss in connection string and you will have certificates on your server.

**Comment by tanmynguyen** [comment]
@noris666 how to use it?

**Comment by noris666** [comment]
@tanmynguyen Buy or get free SSL certificate and then you will need to setup web server (apache, nginx).

**Comment by tanmynguyen** [comment]
@noris666 Hi. I have file ***.cert? But How to use it?

**Comment by noris666** [comment]
@tanmynguyen 
You can ask about that on Meteor forum or find articles in internet. 
I give to you direction. 
Now our conversation not about react-native-meteor. 
Good luck !

**Comment by tanmynguyen** [comment]
@noris666 OK. Thanks you

**Comment by nikhilgoswami** [comment]
I have certificate installed on my server in url I am using wss://url/websecket even wss://url:port/websocket it still doen't work am I missing something?
