### ISSUE TITLE
Meteor.collection(collectionName).find().sort().limit(1)

### ISSUE THREAD

**Issue by nyxynyx** [inProgress-team/react-native-meteor#184]
I'm trying to use `.limit(1)` to retrieve just the most recent document inserted into the collection

    Meteor.collection('zoo').find().sort({createdAt: -1}).limit(1)

However, this throws an error

    undefined is not a function (evaluating '_reactNativeMeteor2.default.collection('zoo').find().limit(1)')

Has the `.limit` function not been implemented?

**Comment by noris666** [comment]
@nyxynyx i use limit inside options.
Look this URL: http://docs.meteor.com/api/collections.html#Mongo-Collection-find

**Comment by grsabreu** [comment]
Limit and other options isn't chained in Minimongo, take a look in the link @noris666 sent
