### ISSUE TITLE
Is there any way to filter the collection used for MeteorListView?

### ISSUE THREAD

**Issue by vantassell** [inProgress-team/react-native-meteor#186]
I have a collection that i'm subscribing to that I want to use as the source for a list view, but I want to filter out some of the results. Is there a way to do this with MeteorListView? 

Is this what the _selector_ is for? Is there some documentation about how to use it?

**Comment by sabativi** [comment]
Yes, it is why the selector is used for.
As an example, see the [README](https://github.com/inProgress-team/react-native-meteor#meteorlistview-component), here you filter document where field is set to done.
