### ISSUE TITLE
Can I choose the name of a collection of a subscription?

### ISSUE THREAD

**Issue by vantassell** [inProgress-team/react-native-meteor#187]
I have a two subscriptions 'courses.enrolled' and 'courses.available' that I want to subscribe to. I'm trying to display the contents of these subscriptions in a MeteorListView but i'm having trouble disambiguating the two subscriptions. If I make a MeteorListView with  'collection=courses.enrolled' or 'collection=courses.available' the collection is not found. Though it seems that both subscriptions are accessible through collection='courses'.

Is there a way to choose the name for the collection of a subscription?

**Comment by eawall** [comment]
Hi @vantassell 

There isn't really a direct relationship between a subscription and a collection in the way that you're thinking. A subscription can handle documents from multiple different collections, and multiple different subscriptions can publish the same documents.

You need to use the `selector` prop of the MeteorListView to pass in a MongoDB query to separate your documents.

Eg.

```
<MeteorListView
  collection="courses"
  selector={{enrolled: true}}
  renderRow={this.renderItem}
/>
```

**Comment by vantassell** [comment]
@eawall That makes sense, I knew i was missing something. Thank you! :)
