### ISSUE TITLE
Meteor offline/online sync ?

### ISSUE THREAD

**Issue by ajonno** [inProgress-team/react-native-meteor#190]
hi, sorry for posting here but we're new to Meteor and need some info fairly quickly. We're building a React Native app for our client. Does this library allow for 'offline first' capability ? i.e. data is persisted on device (iOS or droid) when not connected to internet. Then when back online, the stored data will sync back to Meteor, properly handling updates (latest update wins etc) ?

**Comment by adamgins** [comment]
See this https://github.com/inProgress-team/react-native-meteor/issues/154

**Comment by ajonno** [comment]
thanks will take a look
