### ISSUE TITLE
setInterval, setTimeout, clearTimeout

### ISSUE THREAD

**Issue by wandonye** [inProgress-team/react-native-meteor#192]
I'm converting a Meteor client into React Native codes. With react-native-meteor, the following three functions are not available.

```
Meteor.clearTimeout
Meteor.setTimeout
Meteor.setInterval
```

Any reason why it is not included. What would be an equivalent implementation without these three functions?

**Comment by eawall** [comment]
The equivalent functions are setTimeout, setInterval, clearTimeout, and clearInterval :)

[http://facebook.github.io/react-native/releases/0.40/docs/timers.html#timers](http://facebook.github.io/react-native/releases/0.40/docs/timers.html#timers)

**Comment by wandonye** [comment]
@eawall Ahh~ I thought `Meteor.setInterval` and etc works like session and thus accessible on the server as well. If that's not the case, then Timers in RN will do their jobs.

Another question arises then, is there a way to use `ReactiveVar` with React-Native-Meteor?
