### ISSUE TITLE
Disconnected ddp when remote notification

### ISSUE THREAD

**Issue by 2ducanhpham** [inProgress-team/react-native-meteor#197]
Please help me!

**Comment by noris666** [comment]
Hello ! 
Describe your problem well and i think then you will get most helpful answers :-)
Which platform you use ? 
Which service to distribute notifications ?
I use this package with react-native-onesignal and it is works fine.

**Comment by 2ducanhpham** [comment]
I used React Native 0.40, react-native-meteor 1.0.3, remote pushnotification is raix push (link : https://github.com/raix/push)

**Comment by noris666** [comment]
I use for push notifications OneSignal because it is most simple way.
