### ISSUE TITLE
MeteorListView cannot read property find of undefined

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#20]
I think this probably because of this line

https://github.com/inProgress-team/react-native-meteor/blob/master/src/ListView.js#L40

you are assigning todos in there, so todos just work perfectly but another collections like "channels" etc on mine not working

**Comment by Mokto** [comment]
What a fail ^^

Fixing it now.

**Comment by Mokto** [comment]
Thank you, it is now in 1.0.0-beta9 !
