### ISSUE TITLE
Collection name container '.' breaks sub/pub

### ISSUE THREAD

**Issue by Rhjulskov** [inProgress-team/react-native-meteor#214]
Maybe a minor thing, but as many Meteor developers is naming publication with '.' ect 'users.all_users', I had the issue of getting empty arrays fetched from my publication.

Simply renaming the publication worked.

**Comment by ujwal-setlur** [comment]
Hmm, all my publications use a '.' in them, and it seems to work just fine...

**Comment by Rhjulskov** [comment]
I haven't been trying lately — so might not be an issue :)
