### ISSUE TITLE
How to unsubscribe?

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#22]
How to unsubscribe on componentWillUnmout? We need to unsub it because if not there is warning "set state can only update a mounting or mounted....". Currently I am doing "Meteor.disconnect()" to handle that, but if using it, there will be case that data is not subscribed in another Route. btw I am using "react-native-router-flux" npm package

**Comment by Mokto** [comment]
I just tried and it seems that there is no issue concerning this.

You can look this in examples but :

```javascript
'use strict';


import React, {
  Component,
  StyleSheet,
  View
} from 'react-native';

import Meteor, { connectMeteor } from 'react-native-meteor';
import Button from 'react-native-button';

@connectMeteor
export default class Settings extends Component {
  constructor(props) {
    super(props);

    this.state = {
      show: false
    };
  }
  getMeteorData() {
    return {
      settings: Meteor.collection('settings').findOne()
    };
  }
  render() {
    const { show } = this.state;
    const { settings } = this.data;

    return (
      <View style={styles.container}>
        <View style={{marginTop: 25}}>
        <Button containerStyle={{padding:10, height:45, overflow:'hidden', borderRadius:4, backgroundColor: 'green'}}
                 style={{fontSize: 20, color: 'white'}} onPress={()=>{this.setState({show: !show})}}
          >
            Show : {!show && 'false'}
            {show && 'true'}
          </Button>
        </View>
        {show && <SettingsShow />}
      </View>
    );
  }
}



@connectMeteor
class SettingsShow extends Component {
  startMeteorSubscriptions() {
    Meteor.subscribe('settings');
  }
  render() {
    return null;
  }
}





const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center'
  }
});

```

When SettingsShow are removed, the subscription get canceled ;)

**Comment by radiegtya** [comment]
Have you tried using 'react-router-flux'? because redirecting to another page doesn't automatically unsubscribe

**Comment by Mokto** [comment]
Yeay I did.

The fact is that when you use react-native-router-flux with routes of "push" type, component is not unmounted. It is what is wanted by react-native navigator.

**Comment by radiegtya** [comment]
I did "pop" to unmount my component, and "componentWillUnmount" is trigerred. But still the subscriptions is still there. So when I open another page using same subscribe with different parameter for example, the data from previous component still there

**Comment by Mokto** [comment]
It is really weird, look at my example above.

But if you can provide an example, I might be able to help you ;)

**Comment by radiegtya** [comment]
Here is my code in simple version:

index.ios.js (The Router Main Page)
```javascript
 //... some code
 <Route name="Channels" schema="default" title="Channels" component={Channels}/>
 <Route name="ChannelsAll" component={ChannelsAll} title="All Channel" schema="default"/>
```

Channels.js
```javascript
class Channels extends Component{

 //for example I am just fetching channels which type is public
 getSelector(){
   return {type: "public"};  
 }

startMeteorSubscriptions(){
  Meteor.subscribe('channels', this.getSelector());
}

_renderRow(rowData){
   return (
      <Text>{rowData.name}</Text>
   );
}

render(){
   <MeteorListView
              collection={'channels'}
              selector={this.getSelector()}
              options={{}}
              renderRow={this._renderRow.bind(this)}
              style={styles.listView}
            />
 }
 
}
```

ChannelsAll.js
```javascript
class ChannelsAll extends Component{

 //for example in this component I am getting all channels
 getSelector(){
   return {};  
 }

startMeteorSubscriptions(){
  Meteor.subscribe('channels', this.getSelector());
}

_renderRow(rowData){
   return (
      <Text>{rowData.name}</Text>
   );
}

render(){
   <MeteorListView
              collection={'channels'}
              selector={this.getSelector()}
              options={{}}
              renderRow={this._renderRow.bind(this)}
              style={styles.listView}
            />
 }
 
}
```

and here is the behaviour:

1. When accessing to Channels page by type = "public"
<img width="375" alt="issue-sub1" src="https://cloud.githubusercontent.com/assets/2161622/13799219/065c88f6-eb50-11e5-817f-3a3a876a8ff8.png">

2. When accessing to ChannelsAll, or fetch or channel without selector
<img width="375" alt="issue-sub2" src="https://cloud.githubusercontent.com/assets/2161622/13799235/24e88630-eb50-11e5-988e-bf0d4959dfef.png">

3. Above is just normal and behave like it should be. But when I am hit back button from ChannelsAll to Channels page with "Actions.pop()" method from 'react-native-router-flux', all data is still persist in Channels page although the subscriptions and MiniMongo already using type selector.
<img width="375" alt="issue-sub3" src="https://cloud.githubusercontent.com/assets/2161622/13799274/6ae406d2-eb50-11e5-8d91-3c120e0fbe95.png">

Please help, thanks @Mokto

**Comment by Mokto** [comment]
Indeed this is weird, and even more because you are using a selector { type: 'public' } in your Channels component, right ? So even if the subscription is not unsubscribed, your MeteorListView component should select only the { type: 'public' }.

I will be looking into this, but if you are in a hurry, please create a repo to reproduce this ;)

**Comment by radiegtya** [comment]
yeah the behaviour should be like that, but after changing route, thats just happened. 

is it impossible to create Meteor.unsubscribe()?

**Comment by radiegtya** [comment]
Or something like removeListener on componentWillUnmount() ? Getting memory leak everywhere :(

**Comment by Mokto** [comment]
Yes adding this could be useful in some cases (router-flux routes being pushed), I will add this soon.

But I have to fix this anyway ;)

**Comment by radiegtya** [comment]
Glad to hear. I'll wait. As usual thanks a lot @Mokto, you are life safer. lol

**Comment by Mokto** [comment]
Subscribe now returns an handle (like in Meteor documentation), which is an object with the following properties:
* stop() : to unsubscribe your publication
* ready() : not available yet 

In Beta13

**Comment by Mokto** [comment]
(Feel free to tell me to reopen if necessary)

**Comment by radiegtya** [comment]
Will try this and hope memory leak issue dissapeared

**Comment by java99** [comment]
Hi, 
is this stop() issue completely fixed? 
I am having issues with components that do not unsubcribe (route changed with ex-navigation).
Should I do it manually and how? My handle is not available as this.props.handle.stop.. I get the error "this.props.handle.stop is not a function... undefined.

Thx!

**Comment by radiegtya** [comment]
@java99 : can you give the code example? mine working just fine. btw I am using react-native-router-flux

**Comment by grmmph** [comment]
Hey. Does anyone managed to get over this?
Calling stop() causing an infinite loop.
