### ISSUE TITLE
[Question] How can I save Meteor.userId and Meteor.loginToken to asyncStorage?

### ISSUE THREAD

**Issue by yellowspaceboots** [inProgress-team/react-native-meteor#220]
I was trying to find a reference to saving Meteor.userId and Meteor.loginToken to asyncStorage the same as Accounts saves it to localStorage in the browser. The reason I need this is because the Meteor integration for Apollo Server accepts a header `['meteor-login-token']`, which contains the Meteor.loginToken value, to add the user object to the Apollo "Context". This allows me to pass the user object into my Apollo resolver on every Apollo query or mutation and utilize Meteor packages such as Roles to further authenticate my user's permissions. 

It looks like @spencercarli accomplished this using ddp directly [Here](https://differential.com/insights/meteor-authentication-from-react-native/) but I really like react-native-meteor and was wondering if there was a way to do this utilizing the tools provided here. 

Any help would be appreciated! Thanks!

**Comment by smooJitter** [comment]
You might like this package

https://github.com/DesignmanIO/react-native-meteor-redux

**Comment by spencercarli** [comment]
I actually am working on adding Apollo to my react native + meteor course and figured out a way to basically rebuilding the `meteor/apollo` package in RN. You can check out the [code here](https://github.com/HandlebarLabs/learn-react-native-meteor-source/blob/apollo-support/react-native/app/index.js#L21). Doesn't have batching but the user auth will work as you described!

Let me know if that works for you.

**Comment by yellowspaceboots** [comment]
Thanks guys! 

@spencercarli I was not aware that Meteor's login token was set in asyncStorage automatically! Thanks for your help! This is exactly what I needed.
