### ISSUE TITLE
IPv6 issue on Apple submit

### ISSUE THREAD

**Issue by Nits7029** [inProgress-team/react-native-meteor#232]
Hello,

I am getting an issue on submitting to app store because of IPv6 issue.

I am giving meteor URL "wss://imeyou.io:443/websocket"

So do I need to change anything in URL?

Please help ASAP.

Thanks
Nitesh

**Comment by Nauzer** [comment]
This sometimes happens because of their own wrong network config.
If you just resubmit it will get through most likely.

http://blog.caught.nu/2017/02/Apple-Review-IPv6-Error/#Your-app-is-IPv6-‘Incompatible’-say-whut

**Comment by noris666** [comment]
@Nits7029 it is not react-native-meteor issue, add AAAA record imeyuo.io into DNS zone.
