### ISSUE TITLE
Multiple Build Issues Reported in XCode

### ISSUE THREAD

**Issue by joncursi** [inProgress-team/react-native-meteor#235]
After adding this project to my react native app, I started seeing a lot of build issues being reported in Xcode. The build will succeed, but it looks like there's some cleanup needed related to `RCTWebSocket`:

![screen shot 2017-06-02 at 9 09 37 pm](https://cloud.githubusercontent.com/assets/4974609/26749405/f26d99ee-47d7-11e7-8348-8cf8c5c725a5.png)

**Comment by noris666** [comment]
@joncursi It is not react-native-meteor issue, because we dont have any native code inside package.

**Comment by joncursi** [comment]
Ah, I figured RCTWebsocket made its way into my project via this project. I'll close then
