### ISSUE TITLE
undefined is not a function (evaluating 'this.db.bachtedUpdates')

### ISSUE THREAD

**Issue by renehauck** [inProgress-team/react-native-meteor#238]
Hi, i have this simple code on client side:

...

Meteor.connect('ws://192.168.178.61:3000/websocket');

```
class Main extends React.Component<IndexProps, IndexState> {



    public render(): JSX.Element {
        return (
            <View>
            ....
                {this.props.user && <Text>{this.props.user.Name}</Text>}
            </View>
        );
    }
}

export default Meteor.createContainer(params => {
    Meteor.subscribe('dbuser');

    return {
        user: Meteor.collection('dbuser').findOne()
    };
}, Main)
```

and on server-side, this "publish"-code:

```
Meteor.startup(() => {
  Meteor.publish('dbuser', ()=> {
    return DBUser.find({});
  });
});

```
When i connect the client to the server, i get, for a second, the expected view (the username in a text-tag), and then i get the error : 

```
undefined is not a function (evaluating 'this.db.bachtedUpdates')

_flush
WriteTransaction.js:75:35
....
```
:disappointed:

**Comment by renehauck** [comment]
> Read first, then ask :smirk: 

- `npm i --save-dev babel-plugin-transform-decorators-legacy babel-preset-react-native` in your project

- Create a .babelrc file at the root of your project :

```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```

**Comment by edmundkwok** [comment]
Sorry for reopening this, but I am getting the same error in a fresh RN application, running on the iOS simulator. @renehauck Were you able to get this working on Android / iOS and simulator / on device?

**Comment by renehauck** [comment]
Android device :confused:  

here my package.json:

```
{
 ...
  },
  "dependencies": {
   ....
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-meteor": "^1.0.0-rc14"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "^1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by edmundkwok** [comment]
Thanks for your comment! Glad it's working for you on Android, I guess no joy for iOS simulator 😞 

I've posted the question on `gitter.im` but will post a new issue if needed.
