### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by theomathieubhvr** [inProgress-team/react-native-meteor#245]
Hi,

As I don't develop this project anymore, contributors are needed ! For both repo and npm access.

Who would be interested ?

Thanks.

**Comment by adamgins** [comment]
Phew just posted here https://forums.meteor.com/t/react-native-meteor-looking-for-contributors-needs-community-support/37571 

We're keen to help as we're using this now. Trying to see who else is keen too

@Diwei-Chen

**Comment by Nauzer** [comment]
I would be interested. There are some critical things in this lib that need urgent merging so it would be good to keep up with that.

**Comment by charpeni** [comment]
Hi there,

I'd be surely interested to give a hand if you still need it.

**Comment by Nauzer** [comment]
@theomathieubhvr 
Thanks for adding me. I did the merge for PR243 as I felt that was a necessary change to keep the lib relevant. However I did not bump the version nr to 1.0.4 yet because of missing npm access. Could you help me there?

Greatly appreciated!

**Comment by Mokto** [comment]
Sure, what's your npm username ?

**Comment by Nauzer** [comment]
@Mokto thanks it's "nauzer"

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by theomathieubhvr** [comment]
Just added you.

It would be interesting to follow [semver](http://semver.org/).

1.0.x fix
1.x.0 added functionality
x.0.0 breaking change

Thanks for everything !

**Comment by charpeni** [comment]
@theomathieubhvr If you want to add me on NPM, my npm username is charpeni.

**Comment by Mokto** [comment]
Done !
