### ISSUE TITLE
How can i use FileCollection?

### ISSUE THREAD

**Issue by daominhsangvn** [inProgress-team/react-native-meteor#250]
My backend is using https://github.com/VeliovGroup/Meteor-Files for file management.
How can i use FileCollection from my React-Native?

**Comment by noris666** [comment]
In this case you can use my example posted in FAQ:
https://github.com/VeliovGroup/Meteor-Files#faq

It is not so good implementation, but works :-) 
Now I'm trying to solve this problem not through HTTP POST, but through DDP.

**Comment by daominhsangvn** [comment]
Thanks @noris666 , i will try it

**Comment by Nauzer** [comment]
Although Meteor-Files seems more recently updated I use https://github.com/CulturalMe/meteor-slingshot.

Simple reason: no extra load on the server when uploading files.

**Comment by noris666** [comment]
@Nauzer yep, also good solution. If you can, please share example into example folder in repo :-)

**Comment by Nauzer** [comment]
@noris666 I should correct myself a bit - I used this in my regular Meteor app. Will use it in my react-native-meteor app as well, however I am still working on that. Happy to share an example when I've finalized it.
