### ISSUE TITLE
Difference waitDdpConnected vs. Meteor.ddp.on("connected")

### ISSUE THREAD

**Issue by ayalpani** [inProgress-team/react-native-meteor#251]
Hi,

what is the difference between these two?

```
Meteor.waitDdpConnected(() => {
  console.log("Connected")
})
```

```
Meteor.ddp.on("connected", () => {
  console.log("Connected")
})
```

When should I prefer waitDdpConnected?
Thanks!

**Comment by noris666** [comment]
Hello @ayalpani ! 
Here no difference ! See this file and function source code: https://github.com/inProgress-team/react-native-meteor/blob/master/src/Data.js#L72
