### ISSUE TITLE
Can't Connect to Meteor Production Server

### ISSUE THREAD

**Issue by AdeptLearner123** [inProgress-team/react-native-meteor#254]
I am currently trying to connect a React Native Android app to an external Meteor Production Server, which uses a self-signed SSL certificate. The app is able to connect to the meteor server that is running on the local network. Also, I am able to access the server using the web socket testing app. However, when I try to connect the app to the external Meteor server, the console says "disconnected from DDP server." My connection string is 'wss://XXX.XXX.X.XX/websocket'.

Should I disable logging? Do I need a signed SSL certificate? Any help is appreciated!

**Comment by Nauzer** [comment]
The certificate is probably not on an IP address but on a DNS. Use that.

**Comment by AdeptLearner123** [comment]
@Nauzer 
Is it required that I use an SSL certificate? I am trying to connect by using an IP address.

**Comment by Nauzer** [comment]
Did you try connecting over ws://XXX.XXX.X.XX? 
I would suggest you contact the admin of that server to discuss options.

**Comment by AdeptLearner123** [comment]
Yes I have, and I am the admin of the Meteor server :). Do I need to disable logging in order for the app to be able to connect to a meteor server outside the network?

**Comment by Nauzer** [comment]
Nopes I do it all the time. However I connect on domain name.

I really think it might be an invalid SSL config.
What kind of certificate did you install?
Did you deploy with mup(x)?
Can you share the IP via PM?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AdeptLearner123** [comment]
I generated my (invalid) SSL certificate using openssl. Is that a problem? I did not deploy with meteor up, and I've emailed you my IP. Thanks in advance!

**Comment by Nauzer** [comment]
Thanks for sharing your IP. I connected to your server just fine. 

Can you share your code?
Could be that your network is blocking the connection to an insecure origin? If you try over a hotspot on your phone or stuff you might rule that out.

**Comment by AdeptLearner123** [comment]
Hi Nauzer, thanks for all your help! It was working fine after I installed a real SSL certificate.

Thanks,
Nalu
