### ISSUE TITLE
Meteor.collection('xxx').findOne() return undefined, needed a callback

### ISSUE THREAD

**Issue by vosamoilenko** [inProgress-team/react-native-meteor#259]
When I'm trying to get data I got undefined, but in one second after recalling the method again I get what I want. How I understand, I just wait for a response and when I try to return an object, I have nothing because it is on his way to me. .findOne() hasn't callback, what I can do in this situation?  

`handleLogin = () => {
       Meteor.loginWithPassword(this.state.loginField,this.state.passwordField,(error)=>{
           if (!error) {
           Meteor.subscribe('xxx')
             let data = Meteor.collection('xxxy').findOne();
             console.log(data);
           }
       }
   }
`

**Comment by noris666** [comment]
Hmm first you need login ! Then go to next screen (auth screen types) and then subscribe and get need 4 you data :-) Also better way for get data from subscription it is createContainer. Also another point all good with your meteor connection ?
