### ISSUE TITLE
Connect to multiple DDP

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#27]
How to do this?

**Comment by Mokto** [comment]
Wow sorry but it is not a possibility...

**Comment by radiegtya** [comment]
ok then, I'll close this.

For someone who need to do this for now use this hack in your Meteor Backend

for example I want to call a method from another ddp, make this method in your Meteor.methods backend
```javascript
'callingMethodFromAnotherDDP': function(data){
        var ddp = DDP.connect("https://youranotherddp.com");
        
        var res = ddp.call('Todos.insert', data);
        return res;
 }
```

Thanks @Mokto for the answer

**Comment by Mokto** [comment]
Thanks for the tip and sharing !

I do not think it is something really needed, but if more people need it, I could reconsider but i would have to rework everything.

**Comment by radiegtya** [comment]
for calling a method it just simply like above hack. for subscribe I think it is also easy if using another plugin, for example "ddp-client" and it will not crashing. It's not so important for now, please fix another issue for now :dancer:
