### ISSUE TITLE
Migrate MeteorListView and MeteorComplexListView to FlatList primitive

### ISSUE THREAD

**Issue by mgscreativa** [inProgress-team/react-native-meteor#274]
Hi! Is it possible to migrate the MeteorListView and MeteorComplexListView to the new, performant FlatList? https://facebook.github.io/react-native/docs/flatlist.html

Thanks!

**Comment by jamesloper** [comment]
I just stopped using `MeteorListView` all together. I don't see a problem just removing it!

**Comment by bohan0** [comment]
This is the way to manually do a "MeteorFlatList": https://github.com/inProgress-team/react-native-meteor/issues/246#issuecomment-365025261
