### ISSUE TITLE
Never connects with my phone using 4g

### ISSUE THREAD

**Issue by EstebanBP** [inProgress-team/react-native-meteor#280]
react-native: 0.45.1
react-native-meteor: ^1.0.3
Android - Xiaomi Mi5

Meteor.connect() throws no error.
Meteor.status().connected is always false.

It works well using WIFI but it never connects using 4g.
It works well on other devices I've tried tested (Android and IOS, Wifi or 4g)

Am I missing something?

**Comment by Nauzer** [comment]
What server are you connecting to?
Please share your code fragment.

**Comment by EstebanBP** [comment]
Im just connecting: 
`Meteor.connect('ws://heregoesmyurl.com/websocket');`
`Meteor.ddp.on('connected', () => {Alert.alert('connected')});`

I also tried with some setTimeouts calling Meteor.status().connected but it's always false.

It works in any other devices, and it also works in my phone but only when using wifi

**Comment by EstebanBP** [comment]
I've solved it. 

I think some communication providers/phones (to be honest I do not know if it's related to the provider or the device) don't allow to open socket to insecure server but not error is thrown. I made it work using https and ssl certificate.
