### ISSUE TITLE
how to use on added on removed etc?

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#3]

**Comment by Mokto** [comment]
Hi, it is not possible right now, but I might be adding this very soon.

PRs are welcome too ;)


#5

**Comment by radiegtya** [comment]
I think this is one of important module. Please warn me when it's exists.

**Comment by Mokto** [comment]
Done :)

In release 0.6.0

**Comment by radiegtya** [comment]
Please give some example at readme :+1:

**Comment by Mokto** [comment]
Is that ok for you ?

**Comment by radiegtya** [comment]
Amazing can't wait to test tomorrow.
