### ISSUE TITLE
Accounts Methods

### ISSUE THREAD

**Issue by Mokto** [inProgress-team/react-native-meteor#30]
- [ ] Accounts.verifyEmail(token, [callback])
- [x] Accounts.changePassword(oldPassword, newPassword, [callback])
- [x] Accounts.forgotPassword(options, [callback])
- [ ] Accounts.resetPassword(token, newPassword, [callback])

**Comment by Mokto** [comment]
On second thoughts, verifyEmail and resetPassword have no place in a project like this because you need a token from a link.

What do you think ? @radiegtya @spencercarli @afrantz

**Comment by radiegtya** [comment]
Dunno but still not so important for now. Both can be done without meteor though.

**Comment by radiegtya** [comment]
How about Accounts.createUser?

**Comment by Mokto** [comment]
Accounts.createUser already existing thanks to @spencercarli

**Comment by spencercarli** [comment]
Yeah there are some things we would have to handle on the server to get those working. It would be a nice-to-have but I don't think it should be "blocking" for v1.

**Comment by Mokto** [comment]
Closing this for now then ;)
