### ISSUE TITLE
Use high-order component to replace mixin?

### ISSUE THREAD

**Issue by pomelyu** [inProgress-team/react-native-meteor#300]
Hi,

How about use high-order component to replace the mixin, which is the suggested approach by React official website (https://reactjs.org/docs/higher-order-components.html), and also remove the createClass package.

I have wrote same code to test the concept, and replace `createContainer`
```javascript
export default function createContainer(mapMeteorDataToProps, WrappedComponent) {
  class componetWithTracker extends React.Component {
    getMeteorData() {
      return mapMeteorDataToProps(this.props);
    }

    // the same code in Mixin.js
    
    render() {
      return <WrappedComponent { ...this.data } { ...this.props } />
    }
  }
  componetWithTracker.displayName = `WithTracker(${WrappedComponent.displayName})`;
  return componetWithTracker;
}
```

However `connectMeteor` would no longer work, since `this.data` is located in the high-order component but not in the original component. On the other hand, I think `createContainer` can fully replace `connectMeteor` and use the props to pass data is much more better than access data in the component. If remove `connectMeteor`, react-mixin dependencies can also be removed

Any suggestion?

Thanks

**Comment by charpeni** [comment]
That would be a great improvement, with `createClass` we can't compose and that's a pain.

**Comment by pomelyu** [comment]
I submit a pull request #306

**Comment by charpeni** [comment]
Merged, let's close this. Thank you again.
