### ISSUE TITLE
unexpected url:127.0.0.1:8000/websocket : Cannot connect to my own server url

### ISSUE THREAD

**Issue by CorentinDupont** [inProgress-team/react-native-meteor#319]
Hi, i have a problem when i write this line in my code : 

`Meteor.connect('ws://192.168.9.254:3000/websocket')`

 My android device return the following error : "unexpected url: 127.0.0.1:8000/websocket". My meteor server is running.

**Comment by Nauzer** [comment]
Run  from your android platform-tools dir

adb reverse tcp:3000 tcp:3000

**Comment by CorentinDupont** [comment]
I doesn't seems to change something, i have the same error.

When i run the command in the cmd :
```
C:\Users\Foglo\AppData\Local\Android\sdk\platform-tools>adb reverse tcp:3000 tcp:3000
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
```

When i retry to launch this command, it doesn't do anything.

**Comment by CorentinDupont** [comment]
Hi, i just noticed that i leave this line of code in one of my file : Meteor.connect('http://127.0.0.1:8000/websocket'). Sorry for this mistake. I was surprised that all js files are load at the beginning. So i havn't search in all my files. 

Thanks for your time, good continuation ^^.
