### ISSUE TITLE
[BUG] ANDROID when deleted users or clear resume.loginTokens

### ISSUE THREAD

**Issue by 2ducanhpham** [inProgress-team/react-native-meteor#322]
IOS run ok. But android not working
I not see info
<img width="616" alt="screen shot 2018-08-08 at 2 41 33 pm" src="https://user-images.githubusercontent.com/14899775/43823449-4133a8bc-9b19-11e8-9309-3ea84a118b9f.png">

React-native 0.55.4
React-native-meteor 1.4.0
@noris666

**Comment by vermiculite** [comment]
Hi,
There was a [bug in the react native websocket implementation](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-specific) that meant the close event wasn't being received from the server. Therefore you should upgrade to React-native 0.57.8 or newer and my guess is it will just work.

Let me know how you get on please.

**Comment by 2ducanhpham** [comment]
thanks @vermiculite. I will try

**Comment by 2ducanhpham** [comment]
It fixed with react-native 0.57.8. thanks @vermiculite
