### ISSUE TITLE
How do I change the subscription parameters in the component

### ISSUE THREAD

**Issue by eugle** [inProgress-team/react-native-meteor#326]
Meteor.subscribe('city.by.name’,?)

I want to know how to change the subscription parameters in the component, for example, the city below, according to the user input, how to do

export default withTracker(param => {
    let city = 'sz';
    Meteor.subscribe('city.by.name’,city);
    return {
        list: Meteor.collection('city').find(),
    };
})(App);

Poor English, sorry

**Comment by NoMaxLand** [comment]
Hi @mozibrand ,
I have a similar problem from my app.

My solution : I passe args (like filters) to screenProps of AppNavigator (a "Reduxify" navigation).
Maybe you can take example to resolve your situation ?

Else, have you got found any solution at your problem ? i'm interesting by any suggestions

Poor english too... Hope we understanding us ^^
