### ISSUE TITLE
Cannot read property 'on' of null

### ISSUE THREAD

**Issue by vermiculite** [inProgress-team/react-native-meteor#34]
I had a  working project I believe was 1.0.0beta17 I then upgraded to beta18 and now I get this error. Strangely if I downgrade to beta 17 it has the problem in issue #32.

![simulator screen shot 20 mar 2016 16 56 17](https://cloud.githubusercontent.com/assets/1383259/13905321/e6d4d37e-eebc-11e5-8865-7f914ce1909b.png)

**Comment by Mokto** [comment]
Ok, I'm working on it !

**Comment by Mokto** [comment]
Are you sure you are on version 1.0.0-beta18 ?
Because when I look at 1.0.0-beta18, L20 of Data.js is     `} else {` and L116 of Mixin.js is blank !

Thanks

**Comment by vermiculite** [comment]
oops beta16 my bad sorry!

**Comment by Mokto** [comment]
No problem :)

I'm closing this then.
