### ISSUE TITLE
Meteor.ddp.on is not working

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#35]
my Meteor.ddp.on('changed') etc is not working, please help

**Comment by Mokto** [comment]
I will test this soon !

I'm curious, why do you need ddp listeners for ?

**Comment by radiegtya** [comment]
dunno is this still needed or not because your minimongo cache is stable enough right now. 

But I can say that sometime this is needed for some case like:

- realtime local notification when not using GCM or APN.
- caching chat data. This is hard to explain LOL.
example: only subscribe some data which date $gt latestSavedDateOnCache, then on added, save data to cache but don't add data to cache while the data are from currentLoggedIn user, because data from currentLoggedIn user are saved when pressing send message.  (btw this can be done with current react-native-meteor beta though)

**Comment by spencercarli** [comment]
Haven't tested this but I would also like to advocate exposure of the ddp listeners for things like hooking the data into redux rather than minimongo

**Comment by Mokto** [comment]
@radiegtya What do you mean by "not working" ?

The only condition to use Meteor.ddp.on is to execute Meteor.connect before you execute Meteor.ddp.on.

Is this what you do ? Because every listener is working in my case.

**Comment by radiegtya** [comment]
I think it just working without calling meteor.on connect first. I"ll try

**Comment by radiegtya** [comment]
@spencer I don't think so that we can store data to redux with Meteor.ddp.on too, because the data run too fast and can't wait while the async saving the data, because i have tested it when using ddp-client npm package. dunno that i have wrong code or it just not working

**Comment by spencercarli** [comment]
@radiegtya I haven't had any issues with speed. I don't write to AsyncStorage whenever the redux state changes though.

**Comment by Mokto** [comment]
Can I close @radiegtya ?

**Comment by radiegtya** [comment]
@spencercarli : I haven't tested using redux storage, but if it can be saved, then I am glad to hear
@Mokto : ok I'll close this, thanks
