### ISSUE TITLE
Thoughts on simplifying the examples meteor app

### ISSUE THREAD

**Issue by spencercarli** [inProgress-team/react-native-meteor#37]
It's currently using webpack and possibly other technologies (I haven't actually gotten it running). Would it be worth it to put together a more simple example to demonstrate the power of this package?

**Comment by Mokto** [comment]
Yes, sure ! And we would have to add docs because example apps are only useful to me. It is my way of testing all of it ^^

If you have something in mind, you can work on it, but examples should test every react-native-meteor function in my opinion.

**Comment by spencercarli** [comment]
Agreed that it needs to demo every piece of functionality. I'd be happy to put something together (will likely start with a branch of [this](https://github.com/spencercarli/react-native-meteor-boilerplate)) but can't promise a definitive timeline right now

**Comment by Mokto** [comment]
Well, do it when you have time available, it is nice enough to help this repo. :)

You can branch your repo if you want, your meteor dir is clearly easier than mine :P

**Comment by smooJitter** [comment]
Thank you for the work you're do with this.

**Comment by spencercarli** [comment]
Not ready for a PR yet but I've started on an example app here https://github.com/spencercarli/react-native-meteor

**Comment by Mokto** [comment]
It seems to be good !

Some questions :
* I did not know about file:../.. in package.json in your RNApp. How is it working ? I thought that files had to be at least in the root directory of the project.
* [This file](https://github.com/spencercarli/react-native-meteor/blob/master/example/MeteorApp/server/methods.js) is useless right ?
* The Meteor.FSCollection(collectionName) method to try I think is Meteor.FSCollection(collectionName).findOne().url()

But thanks for this !

**Comment by spencercarli** [comment]
- It seems to work fine so far. I didn't know about it either until seeing [this](https://docs.npmjs.com/files/package.json#local-paths) on npm.

- The file you referenced is exposing methods that are used to test `Meteor.call`

**Comment by Mokto** [comment]
Closing this. Thanks again !

**Comment by smooJitter** [comment]
Ok, I'm running the updated Example.  The list view routes hang on "Loading".  Note, I am running meteor 1.3

**Comment by funkyeah** [comment]
@smooJitter did you resolve this? I'm seeing the same thing, where the app does not appear to be connecting to the meteor server...

In RNApp/app/connect.js there is a url which is default: `http://localhost:3000/websocket`
My meteor server is running at `http://localhost:3000/`

I tried with an without the websocket but still didn't work for me

**Comment by spencercarli** [comment]
If you're running on an android make sure to use your machine's IP address rather than `localhost`

**Comment by funkyeah** [comment]
Thanks @spencercarli this was my issue although with a slight twist, leaving the details here for any other lost travelers:

I am using the genymotion simulator which runs in an Vbox VM. This VM has a host-only network interface. I needed to point the react app to this IP address which was listed as the `vboxnet0` interface when running `ifconfig`

so `http://IPofvboxnet0:3000/websocket` was the final answer for me when using the Genymotion simulator, while the standard IP address of my machine was the correct answer when running on my device
