### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by vermiculite** [inProgress-team/react-native-meteor#38]
Hi @Mokto I would like to add unit tests if that is ok. I have forked the repo and am adding tests in the fork. Are you interested in having unit tests? If so is it best to do it in a fork? Do you have any preferences of testing framework etc I should take into account?

**Comment by Mokto** [comment]
Wow, it would be really nice !

I'm no expert in unit tests but I think [Enzyme](https://github.com/airbnb/enzyme) is the best way to go to test React Components. To test the Meteor logic, well I am open to suggestions :P

**Comment by Mokto** [comment]
Please fork my repo and make PR when you think it is ready enough ;)

**Comment by vermiculite** [comment]
@Mokto I am on it.

**Comment by Mokto** [comment]
Thanks ! ;)

**Comment by Mokto** [comment]
Hi @vermiculite, any update on this ? :)

**Comment by vermiculite** [comment]
Hi @Mokto I set up for unit testing and did four tests. Then I got distracted sorry. I can't honestly see me making much more progress. Should I make a pull request with what I have done and you can decide what to do?

**Comment by Mokto** [comment]
Yeay. If you can't make more progress, then make a PR, and I will see what I can do.

Thanks ;)
