### ISSUE TITLE
this.userId is not defined on Meteor.call

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#39]
if you have method on server like this, you can't get the "this.userId" variable although the client has been logged in

```javascript
Meteor.methods({
   getSomething: function(){
      console.log(this.userId); //this return undefined
   }
});
```

I think this should be on 1.0 @Mokto . Thanks a lot

**Comment by Mokto** [comment]
I confirm this works in 1.0.0-beta19.

I just added an example if you can run it.

**Comment by radiegtya** [comment]
Glad to hear, will try this soon

**Comment by Mokto** [comment]
Closing issue for now then.

**Comment by radiegtya** [comment]
Cool it's all working not only this.userId

```javascript
'fetchUserData: function(){
        return {
            userId1: Meteor.userId(),
            userId2: this.userId,
            user: Meteor.user()
        };
    },
```

it can return all the value. thanks @Mokto
