### ISSUE TITLE
Subscription_Error

### ISSUE THREAD

**Issue by ignivanishant** [inProgress-team/react-native-meteor#4]
We done with making successful connection with react-native, but while subscribe to a collection its return an array object for first time, then after immidiate its return an empty array along with "NO SUB" log.

**Comment by Mokto** [comment]
Hi,

I would like to know a little bit more about what you're doing exactly.

Can you post your publish (Meteor) and susbscribe (react-native) fonction please ?

**Comment by Mokto** [comment]
Are you sure you removed autopublish meteor package ?

**Comment by radiegtya** [comment]
I think this is not valid question anymore. Would you mind to close this to make issues clear?

**Comment by Mokto** [comment]
No I do not. @ignivanishant feel free to reopen if any issue ;)
