### ISSUE TITLE
Support for non-websocket DDP connections

### ISSUE THREAD

**Issue by ndarilek** [inProgress-team/react-native-meteor#44]
Maybe this already exists and I'm missing it. I'm routing my app traffic through the free CloudFlare plan which doesn't support websockets. I attempted to get a plain HTTP connection working but could not.

Thanks!

**Comment by Mokto** [comment]
Hi,

No it's not supported right now.

I do not know how this works, but I'm using [ddp.js](https://github.com/mondora/ddp.js/). Maybe you could change Websocket constructor ?

Please let me know if you succeed.
