### ISSUE TITLE
@connectMeteor throwing Unexpected token

### ISSUE THREAD

**Issue by smooJitter** [inProgress-team/react-native-meteor#45]
Can you explain the purpose of @connectMeteor expression.  I've install the Babel presets and I have the fill with the following, 
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
When I remove the reference, it appears the ddp connection fails?

**Comment by Mokto** [comment]
Hi,

@connectMeteor is a mixin which enables getMeteorData to be taken into account.

Is has nothing to do with `Meteor.connect(url)`, so ddp connection should not fail.

What version of RN are you using ?

**Comment by smooJitter** [comment]
I'm running RN 0.22.0 and used npm3 to install.   I trying  run this code from a forked repo,

The simulation hangs on ' Connecting to the Server'  The console.log reported 'CONNECTED'.  When I console.log(this.data), I see status: disconnected.

https://github.com/spencercarli/react-native-meteor/blob/master/example/RNApp/app/index.js
```
import SignIn from './containers/signIn';
import SignOut from './containers/signOut';
import Items from './containers/items';
import Tabs from 'react-native-tabs';

import Meteor, { connectMeteor } from 'react-native-meteor';

@connectMeteor
export default class RNApp extends Component {
  constructor(props) {
    super(props);

    this.data = {
      status: {},
      user: null
    }
    this.state = {
      page: 'account'
    }
  }

  componentWillMount() {
    const url = 'http://localhost:3000/websocket';
    Meteor.connect(url);
  }

  getMeteorData() {
    return {
      status: Meteor.status(),
      user: Meteor.user()
    };
  }

  renderAccountPage() {
    const { status, user } = this.data;
    if (user) {
      return <SignOut />;
    } else {
      return <SignIn />;
    }
  }

  render() {
    const { status, user } = this.data;
    const { page } = this.state;

    if (!status.connected) {
      return (
        <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
          <Text>Connecting to Server...</Text>
        </View>
      );
    }

    let SelectedComponent = null;

    if (page === 'account') {
      SelectedComponent = this.renderAccountPage();
    } else if (page === 'items') {
      SelectedComponent = <Items />;
    }

    return (
      <View style={styles.container}>
        {SelectedComponent}
        <Tabs
          selected={this.state.page}
          style={styles.tabStyle}
          selectedStyle={styles.tabSelectedStyle}
          onSelect={el=>this.setState({page:el.props.name})}
        >
            <Text name="account">Account</Text>
            <Text name="items">Items</Text>
        </Tabs>
      </View>
    );
  }
}
```

**Comment by Mokto** [comment]
1) Remove 
```
this.data = {
      status: {},
      user: null
    }
```
from your code

2) Try it with last react-native-meteor version. Not a fork.

**Comment by smooJitter** [comment]
Thanks for replying, installed the latest version of react-native-meteor. The example code however is from the fork. When removed the code above, I observed to things. When I also remove @connectMeteor, I get and error saying the 'status' property is undefined.   However, when I follow your direction above and keep in place the "connectMeteor'  I still get an error 

'Unexpected token(10:0)'

which references the @connectMeteor statement.

**Comment by Mokto** [comment]
Yeay that means you didn't install babel presets properly.

If you want you also can use 

```javascript
class Todos extends Component {
    ...
  }
  connectMeteor(Todos);
  export default Todos;
```

**Comment by smooJitter** [comment]
Now I receive at Unexpected error at '...'

**Comment by smooJitter** [comment]
We can close this.  I got everything working.  I restarted react packager and that seemed to have done the trick.

**Comment by Mokto** [comment]
Perfect

**Comment by radiegtya** [comment]
not working on latest version. 

btw this is working:
```
connectMeteor(SomeClass);
```

but not this:
```
@connectMeteor
```

**Comment by Mokto** [comment]
this is working in my case. Did you update react-native preset npm version ?

**Comment by ubatin** [comment]
`connectMeteor(SomeClass)` is worked for me.
