### ISSUE TITLE
Example for uploading image by using FSCollection

### ISSUE THREAD

**Issue by bubuzzz** [inProgress-team/react-native-meteor#50]
I am stuck with uploading image to the server. When i trigger the command 
> Meteor.FSCollection('images').insert({url: fileObj}, function(err, res) {
>             if (err) {
>                 console.log('error during uploading'); 
>             } else { 
>                 console.log('uploading successfully');
>                 // _this.props.navigator.pop();
>             }   
>});

It will give me the exception `Meteor.waitDdpConnected is not a function`.  However, if i comment the part of uploading the image and do a call normally to insert the data, it works

**Comment by Mokto** [comment]
Should be fixed in 1.0.0-beta26.

;)

**Comment by bubuzzz** [comment]
Thank buddy. Really looking for it :dancer:

**Comment by bubuzzz** [comment]
@Mokto sorry to wake you up in the closed ticket. I cannot find any way in order to post the image from the phone to the server

the collection on the server is 

```
Images = new FS.Collection("images", {
    stores: [new FS.Store.FileSystem("images", {path: "~/uploads"})]
});

Images.allow({
    'insert': function () {
        // add custom authentication code here
        console.log('image inserted');
        return true;
    }
});

```

And in my event handler in RN app 

```
var photo = {
            url: fileObj,
            type: 'image/jpeg',
            name: 'photo.jpg',
};


Meteor.FSCollection('images').insert(photo, function(err, res) {
    if (err) {
        console.log('error during uploading'); 
    } else { 
        console.log('uploading successfully');
        _this.props.navigator.pop();
    }   
});

```

I can see the log `uploading successfully` and see the new record in `cfs.images.filerecord` collection, but in the `uploads` folder, it is empty

**Comment by Mokto** [comment]
Did you try to access your uploaded object with object.url() ? Does it work ?

**Comment by bubuzzz** [comment]
@Mokto Sorry for the late reply. i am working on the issue today and will report to you later. Thank you very much for your awesome project

**Comment by bubuzzz** [comment]
Hi @Mokto is there anything wrong with my code ? 

```
Meteor.FSCollection('images').insert(photo, function(err, res) {
    if (err) {
        console.log('error during uploading'); 
    } else { 
        console.log('uploading successfully');
        console.log(res);
        _this.props.navigator.pop();
    }   
});

```

only return the Id. I did see the `cfs.images.filerecord` is generated and has the new data in it. For example 

```
{
	"_id" : "aCcd4NK39fdQoinWF",
	"uri" : "/Users/bubuzzz/Library/Developer/CoreSimulator/Devices/56D747C4-B5DE-42BD-A8DC-89CA6DBBB02A/data/Containers/Data/Application/ADDC0D76-DF8A-40C2-90B3-76C6DF5446FA/Documents/2809D2AE-9E23-4B72-AFC4-D5D9A7C37329.jpg",
	"type" : "image/jpeg",
	"name" : "2809D2AE-9E23-4B72-AFC4-D5D9A7C37329.jpg"
}
```
which is not correct. What is the correct way to set into the variable for the `Meteor.collection('images').insert(....)`

**Comment by bubuzzz** [comment]
And i tested from a page on my website and it actually can work, therefore, i don't think there is anything wrong with my backend setting

**Comment by bubuzzz** [comment]
i think the problem is the input for the FSCollection is not correct. I am using `react-native-camera` and it returned a `asset-library` or a `uri`, however, i cannot use those in order to put into `Meteor.FSCollection('images').insert()`

**Comment by radiegtya** [comment]
This is a bug, although passing base64 data, still not working. For now I am using meteor.call and insert using fs insert meteor way

**Comment by Mokto** [comment]
Sorry for late replying. I have no time for this right now, so I would appreciate that someone fix this for me ;)

**Comment by Mokto** [comment]
FSCollection is now deprecated, so I'll close this.

BTW, has anyone found a good replacement library ?

**Comment by noris666** [comment]
@Mokto i replace CollectionFS to CFS. Maybe try this package ?

**Comment by noris666** [comment]
@Mokto what you think about VeliovGroup/Meteor-Files ?

**Comment by Mokto** [comment]
This is the one I use, but it has definitely not the power of CollectionFS.

**Comment by gauravdhiman** [comment]
If `CollectionFS` is deprecated, then what is the recommended package for file uploading to Meteor from React / Reat-Native ?

Last comment on this was one year back, I hope by now someone must have found a better way to upload files from React / React-Native to Meteor.

Will appreciate if you can share your experience.
