### ISSUE TITLE
You forgot to turn off debug (console.log) on latest beta27

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#52]
I think this is a little bit annoying for debugging

<img width="1268" alt="bug-rn-beta27" src="https://cloud.githubusercontent.com/assets/2161622/14550003/3699052e-02ef-11e6-931e-75981dee2706.png">

**Comment by patrickml** [comment]
Console logging also causes huge performance problems when lots of items are added, anyway this can be made a config when doing Meteor.connect?

**Comment by Mokto** [comment]
Sorry, fixed in 1.0.0-beta28.

**Comment by patrickml** [comment]
@Mokto thanks for the quick fix. is there a way to enable it? I think it's useful for when you need to see the data, just having the ability to turn it On/Off is optimal.

**Comment by Mokto** [comment]
You can do
```javascript
Meteor.ddp.on('added', message=>{

});
```

;)

**Comment by patrickml** [comment]
Perfect thank you
