### ISSUE TITLE
Meteor.userId() always returns someone's user id even if not logged in.

### ISSUE THREAD

**Issue by saeho** [inProgress-team/react-native-meteor#53]
Using userId() method, it will always return some user's id. When I delete the document that this method returned, it just returns someone else's id.

**Comment by saeho** [comment]
**Note

This is happening because I was subscribing to the users collection.

However I was not logged in at the time. But because I was subscribing to the users collection, Meteor.userId() returned someone's user Id that wasn't mine.

**Comment by Mokto** [comment]
Hi,

Thanks for reporting this.

It should be fixed in 1.0.0-beta28.
