### ISSUE TITLE
No Result in Meteor.loginWithPassword

### ISSUE THREAD

**Issue by patrickml** [inProgress-team/react-native-meteor#54]
there isnt a res in the callback for `loginWithPassword` making it hard to tell if the login was sucessful

**Comment by Mokto** [comment]
Sorry but I respect Meteor accounts package.


[See http://docs.meteor.com/#/full/meteor_loginwithpassword](http://docs.meteor.com/#/full/meteor_loginwithpassword)

**Comment by patrickml** [comment]
Ah didn't see that, i thought it did have a result thank you.
