### ISSUE TITLE
beta30 installation issues. 

### ISSUE THREAD

**Issue by smooJitter** [inProgress-team/react-native-meteor#57]
FYI

This is happening  when trying run the example:

npm ERR! addLocal Could not install /Users/jitter
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm3/node_modules/npm/cli.js" "install"
npm ERR! node v4.3.0
npm ERR! npm  v3.7.5
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

**Comment by Mokto** [comment]
It is weird, I never seen such message and it is working fine for me.

Did you try to rm -rf node_modules and then npm install ?

**Comment by Mokto** [comment]
Is it ok now ?

**Comment by smooJitter** [comment]
Yes

**Comment by Mokto** [comment]
Can you please try :
* rm -rf node_modules
* install 1.0.0-beta32

**Comment by Mokto** [comment]
Closing this for now. Try with release candidate ;)
