### ISSUE TITLE
Help understand @connectManger

### ISSUE THREAD

**Issue by smooJitter** [inProgress-team/react-native-meteor#58]
I have a few quests.   Can you explain what's happening with the @connectMetero.   Whatpoint and how is it carried out in this context?  Also,  in the example app, where is "this.data" coming from? Is it related to @connectMeteor.

**Comment by Mokto** [comment]
@connectMeteor takes into account getMeteorData() and populates the *reactive* object return by getMeteorData into this.data.

Is that clear enough ? :)

**Comment by smooJitter** [comment]
So what ever we get from by invoking getMeteorData, the results are already reactive?  That's nice!  

I have a question then, What if we want to grab non-reactive data via a method call. Or what if I wanted to use something like[ react-komposer](https://github.com/kadirahq/react-komposer) to build react container components.  The aim is to decouple the view, data, and application logic. 

I tried a few things an  connectMeteor decorator throws and error if it is not attached to a traditional react component invocation.

**Comment by smooJitter** [comment]
Specifically, How can I make something like this work?
===============================
import Trackr from 'react-native-meteor';
import { composeWithTracker } from 'react-komposer';
import Post from '../components/post.jsx';

function composer(props, onData) {
  const subscription = Meteor.subscribe('post', props.postId);

  if (subscription.ready()) {
    const data = {
      ready: true,
      posts: Posts.findOne(props.postId).fetch()
    }
    onData(null, data);
  } else {
    onData(null, {ready: false});
  }
}
export default composeWithTracker(composer)(Post);
================================

Apparently getMeteorData() works with Meteor's ReactMixin, with from what I can tell, doesn't maintain enthusiastic support.  The code above was taken from this article, which provides a few alternatives,  all but one encourages a react containers approach where data is passed to dumb components via properties.  

https://www.discovermeteor.com/blog/data-loading-react/

**Comment by grsabreu** [comment]
@smooJitter, `composeWithTracker` assumes that `Tracker` is available to use, I guess that a `composeWithTrackr` would solve your problem:

```
import Trackr from 'trackr';
export function composeWithTracker(reactiveFn, L, E, options) {
  const onPropsChange = (props, onData) => {
    let tracerCleanup;
    const handler = Tracker.nonreactive(() => {
      return Trackr.autorun(() => {
        trackerCleanup = reactiveFn(props, onData);
      });
    });

    return () => {
      if (typeof (trackrCleanup) === 'function') {
        trackrCleanup();
      }
      return handler.stop();
    };
  };

  return compose(onPropsChange, L, E, options);
}
```

Then you could import that file from the Containers code:

```
import { composeWithTrackr } from '/where/you/saved/it.js/;
import Post from '../components/post.jsx';

function composer(props, onData) {
 const subscription = Meteor.subscribe('post', props.postId);

 if (subscription.ready()) {
 const data = {
   ready: true,
   posts: Posts.findOne(props.postId).fetch()
  }
  onData(null, data);
 } else {
 onData(null, {ready: false});
 }
}

export default composeWithTrackr(composer)(Post);
```

**Comment by grsabreu** [comment]
I just have some doubts about that solution.
Would it defer in any way from the getMeteorData solution, @Mokto ? I can see a bunch of logic in the mixin's code and I want to use the komposer solution because whenever I call `onData` within the composer the Container renders.

**Comment by Mokto** [comment]
I'm about to add the official createContainer function that does everything you're asking.

http://guide.meteor.com/v1.3/react.html#using-createContainer

Would it be enough ?

I prefer make this plugin closer to official Meteor doc than community packages.

**Comment by Mokto** [comment]
Closing this since I implemented createContainer but feel free to discuss about it here.
