### ISSUE TITLE
Did Subscriptions support Publish Composite?

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#6]
Did React-Native-Meteor Subscription able to get data from collection which is published by Meteor Publish Composite package? (publish collections with it's relation) so it can get the relational collection?

btw here is the link of publish composite package https://atmospherejs.com/reywood/publish-composite

**Comment by radiegtya** [comment]
I have tested it, and I can't get the related collections published by publish composite. I think this is very important in production. Is it possible?

**Comment by Mokto** [comment]
I do not know yet, but I know I had issues using https://github.com/CollectionFS/Meteor-CollectionFS

I will try your plugin when I'll be less busy. (maybe next monday :) )

Please note that I am thinking more and more about a V1.0 release equivalent to react-meteor plugin. (with startMeteorSubscriptions and getMeteorData mixins).

**Comment by radiegtya** [comment]
Please make sure to make it as similar as real meteor (docs.meteor.com) DDP usage. If it possible, then your plugin will be the best plugin out there, and I think that's possible when looking at your current plugin. 

Currently for production I am using this plugin https://www.npmjs.com/package/ddp-client, and It works pretty well. But unfortunately their code is not really taste like meteor, for some case it's very difficult to be used. 

Thanks

**Comment by radiegtya** [comment]
Hi @Mokto, when will you take a look at this? :dart:

**Comment by radiegtya** [comment]
wow 1.0 coming, I'll try now! and test if this already available!! Good job

**Comment by Mokto** [comment]
:)

My next step is to check your PublishComposite plugin.

Soooon.

**Comment by radiegtya** [comment]
This is already worked on latest version 1.0.0-beta2. Thanks :)
