### ISSUE TITLE
collection(...).find() and findOne() queries do not work with _id

### ISSUE THREAD

**Issue by saeho** [inProgress-team/react-native-meteor#61]
Meteor.collection("NAME").find({_id: "abcdefg"}) and findOne() using _id param does not work.

Also, returned documents do not have _id in them. Is this intended?

**Comment by saeho** [comment]
Never mind. Previous components were conflicting in subscriptions. You have to manually turn off all subs using this package.

**Comment by funkyeah** [comment]
@saeho I'm planning to do a pull request that adds more detail to the documentation. I'm not as far as you in using react-native-meteor and from your description it sounds like a problem I could very easily run into.

The docs say that if you use subscribe in getMeteorData() and later unmount the component, that a unsubscribe will happen automatically?Did you you not subscribe in getMeteorData() and/or how were you subscribing? 

Are you saying that you did the same subscribe in multiple locations and that caused the conflict? or how did you get conflicting subscriptions? 

Any thoughts on what limitations this imposes or how you now plan to handle subscriptions?
