### ISSUE TITLE
FS image.url() is not return correct uri

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#63]
in my case whenever I fetch image.url() from collection FS, my url look like this, which not readable by react-native 
```
http://localhost:3000/cfs/files/files/PmEazLruibjueMQpi?store=files&token=e…RoVG9rZW4iOiIwc2pSenl6dFRqeFc3d2JpTzhHNDB2Rk15UEV2QWZYMXBmeFlMNVBfWl9YIn0=
```

it is missing the file name, so I am hardcoding it like this to be able showing my image

```javascript
const uri = file.url().substr(0, file.url().indexOf("?"))+"/"+file.name(); //add file.name() in the last url
```

so the correct image url will persist
```
http://localhost:3000/cfs/files/files/PmEazLruibjueMQpi/bg.png
```

Please fix this. Thanks

**Comment by Mokto** [comment]
Available in 1.0.0-beta33. Thanks !
