### ISSUE TITLE
Accessing the underlying ListView

### ISSUE THREAD

**Issue by adrianmc** [inProgress-team/react-native-meteor#68]
I've been trying to write a function to scroll to the bottom of the MeteorComplexListView.

Something so ostensibly simple has taken me an entire day, but at least I think I found out why. I googled around for a way to make a ListView scroll down to the bottom and found a few answers. However, none of them worked because they all required a method that the MeteorComplexListView instance didn't have.

That is understandable, because MeteorComplexListView is not a ListView in and of itself. Its render function simply returns one. That means my `ref` to it does not actually touch a ListView component. Hence I can't actually use the functions that a normal ListView would come with.

This is what my component looks like:

```jsx
<MeteorComplexListView
  elements={this.getElements}
  renderRow={this.renderRow}
  renderFooter={this.renderFooter}
  contentContainer={{paddingVertical: 20}}
  ref={r => this._listView = r}
  onLayout={(event) => {
    var layout = event.nativeEvent.layout;
    this.listHeight = layout.height;
  }}
  onContentSizeChange={(width, height) => {
    this.contentHeight = height;
  }}
/>
```

And this is the function I'm trying to use to scroll to the bottom:

```jsx
scrollToBottom() {
  if (this.listHeight && this.contentHeight && this.contentHeight > this.listHeight) {
    const scrollDistance = this.contentHeight - this.listHeight;
    this._listView.getScrollResponder().scrollTo({
      y: scrollDistance,
      animated: true,
    });
  }
}
```

In the above, `this._listView.getScrollResponder()` would throw and error:

```
this._listView.getScrollResponder is not a function
```

Do you think it would be sensible to implement a `getListViewRef()` function inside the MeteorListView and MeteorComplexListView components? This allows people to *really* use this library as if they were dealing with a ListView.

It would likely involve something simple like adding this to the props of the ListView:

```jsx
ref={r => this._listView = r}
```

And adding a function in the component like this:

```jsx
getListViewRef() {
  return this._listView;
}
```

For the record, I've done this and it seemed to have worked for my use case. I will submit a PR if people think it's a good idea.

**Comment by Mokto** [comment]
Thanks.

listViewRef prop now in 1.0.0-rc2.

Let me know is something not working or still missing ;)

**Comment by zyonnetworks** [comment]
How do i set/get the 'refs' of each item via renderRow as  described here: https://github.com/facebook/react-native/issues/897
