### ISSUE TITLE
EJSON parameter support

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#7]
Using Meteor.call and Meteor.subscribe parameter is very important for production apps.
For now the parameter still only able to pass strings of object. We can't pass value like integer, Date etc. Maybe we need to make EJSON support.

If I am not wrong we can use this npm package https://www.npmjs.com/package/ejson.

For example:

```
var filters = {
   createdAt: {$gt: new Date()},
   vote: 5
};
filters = EJSON.stringify(filters); //stringify the object first
filters = EJSON.parse(filters); //make to EJSON obj
Meteor.subscribe('some_collections', [filters], function(someCollections){
   console.log(someCollections);
});
```

I think the above code should be simplified in "react-native-meteor" module instead manually doing that.
Regards

**Comment by Mokto** [comment]
Looking up soon ;)

**Comment by radiegtya** [comment]
This is still happened on v1.0.0-beta2.

when I am doing this subscriptions:
```
  Meteor.subscribe('messages', {channelId: "general", createdAt: {$lt: new Date()}}, {limit: 1});
```

then I am doing console.log on server 

```
console.log(typeof(selectors.createdAt.$lt))
```

the date selectors still have a String value, which it should be Object/Date, and this can be achieved with EJSON. Any plan on upgrading this?

**Comment by Mokto** [comment]
Hi,

I'm not really familiar with EJSON. But I can EJSON.stringify every parameter sended in subscribe.
The issue is that the meteor server must EJSON.parse the parameters, right ? This plugin has no control on the meteor server. How can I do ?

Pull requests or advices are welcome ;)

**Comment by radiegtya** [comment]
yeah for now I am still able to do this manually like this

in react native apps:
```javascript
  startMeteorSubscriptions() {
    var filters = {
       createdAt: {$lt: new Date()},
    };
    filters = EJSON.stringify(filters); //stringify the object first
    Meteor.subscribe('todos', filters);
  }
```

in Meteor server side:
```javascript
Meteor.publish('todos', function(selector){
    var selector = EJSON.parse(selector);
    return Todos.find(selector);
});
```

Btw have you take a look at this plugin? I can use their Meteor call and Meteor subscribe without passing EJSON, and it works just fine. https://www.npmjs.com/package/ddp-client.

I think we should take a look at their source code about how to do that

**Comment by Mokto** [comment]
https://github.com/hharnisc/node-ddp-client/blob/master/index.js#L112

They stringify the data before sending it. But I do not want to force people to EJSON.parse in server methods.

What do you think ?

**Comment by radiegtya** [comment]
No they also don't make people need to EJSON.parse in their server methods. They are not only stringify it on client, but also able to make server automatically parse it, still dunno where is the code take place

**Comment by radiegtya** [comment]
maybe this line 

```javascript
self.socket.send( //<<------ this code, will handle the obj parse
  EJSON.stringify(data)
);

**Comment by Mokto** [comment]
I do not think so, because they use Websocket like in ddp.js.

I'm lost ^^

**Comment by radiegtya** [comment]
Is this will not be reworked? Any Info?

**Comment by Mokto** [comment]
I would like to, but I do not know how to do it yet.

**Comment by Mokto** [comment]
I just saw this PR from ddp.js plugin.

https://github.com/mondora/ddp.js/pull/19

Maybe this can help, will look if this works soon.

**Comment by radiegtya** [comment]
nice tell me when it has available

**Comment by Mokto** [comment]
Done ! ;)

**Comment by radiegtya** [comment]
Good job!!! I'll try tonight (Indonesian Time :waning_crescent_moon: )

**Comment by radiegtya** [comment]
Thanks, this works perfectly!
