### ISSUE TITLE
Access user collection

### ISSUE THREAD

**Issue by dnish** [inProgress-team/react-native-meteor#73]
Hi,
I'm having a strange issue. I'm publishing my posts via <code>Meteor.publishComposite</code>. In my React Native app I can access every published data for that post (f.e. Comments) without problems, but when I try to access users:

```
   //After subscription is ready - works fine with Comments collection
   console.log(Meteor.collection("users").find());
```

I only get an empty array. This is our publish method:

```
Meteor.publishComposite("posting", function(id) {

    return {

        find: function() {
            return Postings.find({_id:id, isVisible:true,fileReady:true},{limit:1});
        },

        children: [{

            find: function(post) {
                return Meteor.users.find({_id:post.userId});
            }
        },

            {
                find: function(post) {
                    return Comments.find({postingId:post._id});
                },

                children: [{
                    find: function(comment) {
                        return Meteor.users.find({_id:comment.userId});
                    }
                }]
            }
        ]


    }
});
```

Do I miss something here?

**Comment by Mokto** [comment]
This is weird.

I have never used publishComposite so I don't really know how it is going with this.

I will be looking into this soon.

**Comment by Mokto** [comment]
Can you please post a fork of the example provided in this repo with this bug ? Thanks !

**Comment by dnish** [comment]
@Mokto Sorry for not answering this, but it seems fixed or was the mistake on our side. In our latest app, everything is working fine.

**Comment by liberatomota-itcenter** [comment]
Hello, 

In my app i can access all the collection but the users. Always returns `null`.

Client code:
```
export default createContainer(() => {
let terminals;
let subTerminals = Meteor.subscribe('terminals', Meteor.userId() );
if(subTerminals.ready()){
console.log("HIS READY"),
   terminals = Meteor.collection('terminals').findOne( Meteor.userId() );
}

return {
    status: Meteor.status(),
    user: Meteor.user(),
    loggingIn: Meteor.loggingIn(),
    terminals: terminals,
    tests: Meteor.collection('tests').findOne('6XJNau7tF5jZwnnTk')
  };
}, App);
```

Server code:
```
export default() => {
    Meteor.publish('terminals', (userId) => {
        console.log("userId", userId);
        return Meteor.users.find({_id:userId})
    })
}
```
My Meteor.user() in the client returns the user object but when I try to get a user through a publication. The test subscription (exactly the same just pointing to a "tests" collection) works fine.

Any help will be appreciated!
Thanks

**Comment by bockc** [comment]
I have a similar problem. 
My published collection `users` only gives me access to the current logged in user, which seems alright to me according the following publish
```
Meteor.publish("users", function users() {
	return [
		Meteor.users.find(
			this.userId,
			{
				fields: {
					school: 1,
					emails: 1
				}
			}
		),
		Plannings.find({ ownerId: this.userId }),
		CounsellingProfiles.find({ ownerId: this.userId })
	];
});
```

Now the real trouble is, to test things I have a publish `allUsers` publishing all users like this
```
Meteor.publish("allUsers", () => Meteor.users.find());
```

But whenever in my react-native app I try to access `allUsers`, like this
```
Meteor.subscribe(
     'allUsers',
     error => console.log(error),
     () =>
       this.setState({
         users: Meteor.collection('allUsers', { cursoredFind: true })
           .find()
           .fetch(),
       }),
   )
```
I always receive a null object. I don't understand what could be wrong in this code, as I successfully did that with several other collections and it worked perfectly fine.
Any idea what could cause this ?


Update:
I finally managed to get it working. 
One of the problems was that I was subscribing to the publish named `allUsers` but called `find()` on the the collection `allUsers`, which does not exist, instead of the collection `users`. Silly me.

Another problem I had when trying to do what I wanted was I had to subscribe to multiple publishes and find data in multiple collections in my redux action. I achieved this with the following
```
const fetchTicketsSuccess = (limit, offset) => ({
  type: 'FETCH_TICKETS_SUCCESS',
  data: Meteor.collection('ticket')
    .find({}, { limit, skip: offset })
    .map(item => ({
      ...item,
      auteur: Meteor.collection('users').findOne({ _id: item.auteur }),
      key: item._id,
    })),
});

const fetchTickets = (options = {}) => (dispatch, getState) => {
  if (options.reset) dispatch(fetchTicketsReset());

  dispatch(fetchTicketsRequest());

  const { limit, offset } = getState().userAppsReducer.ticketsReducer.allTicketsReducer;
  Meteor.subscribe(
    'ticket',
    error => dispatch(fetchTicketsError(error)),   //tickets subscribe failed
    () =>    //tickets subscribe successful
      Meteor.subscribe(
        'allUsers',
        err => dispatch(fetchTicketsError(err)),   //users subscribe failed
        () => dispatch(fetchTicketsSuccess(limit, offset)),  //users subscribe successful, can now fetch all the data I need :)
      ),
  );
};
```
