### ISSUE TITLE
console.error: "Exception from Trackr recompute function:

### ISSUE THREAD

**Issue by smooJitter** [inProgress-team/react-native-meteor#74]
I'm getting this code from the current example app

https://github.com/inProgress-team/react-native-meteor/blob/master/example/RNApp/app/routes/meteorListView.js

The only difference, I'm using create container thus

```javascript
export default createContainer( params => {
  const itemsHandle = Meteor.subscribe('items');
  return {
    itemsReady: itemsHandle.ready()
  };
}, SecondTabScreen)

```

![screen shot 2016-05-20 at 2 12 01 pm](https://cloud.githubusercontent.com/assets/13536334/15437497/6e7256f0-1e95-11e6-8d9d-7fd07cb053c9.png)

**Comment by Mokto** [comment]
I think this is because you have an error within your SecondTabScreen component. 

I have to investigate this but Trackr sometimes catch the errors in your components.

**Comment by Mokto** [comment]
This should be fixed in rc7. Please tell me if you get this error again ;)
