### ISSUE TITLE
undefined is not an object (evaluating '_react2.default.addons.batchedUpdates')

### ISSUE THREAD

**Issue by hyperh** [inProgress-team/react-native-meteor#76]
I'm getting the following error
```
undefined is not an object (evaluating '_react2.default.addons.batchedUpdates')
```

on versions
```
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-meteor": "1.0.0-rc4",
```

I believe this is due to the following lines of code
https://github.com/inProgress-team/react-native-meteor/blob/master/src/Data.js#L1
https://github.com/inProgress-team/react-native-meteor/blob/master/src/Data.js#L7

react-native 0.26.x requires you to do `import React from 'react'` rather than `react-native`. However, when I try to import from react, I get the same error. I think this issue is related https://github.com/facebook/relay/issues/127

Based on https://github.com/facebook/react-native/blob/26e84262484767dd9abdfd78ff16fa37fcb8e334/Libraries/react-native/react-native.js#L155

I tried to do 
```
import ReactNative from 'react-native

db.batchedUpdates = ReactNative.batchedUpdates;
```
But I get the error
```
Unable to get cookie from the https://myapp.com/websocket
```

**Comment by Mokto** [comment]
Hi @hyperh,

Thanks for reporting. I just got this error too when testing on Android.
On iOS everything works fine !

I replace RN.addons.batchedUpdates by db.batchedUpdates = ReactNative.unstable_batchedUpdates; and the warning message is not here anymore.

But 
```
Unable to get cookie from the https://myapp.com/websocket
```
is what I get too and I do not think it is related to batchedUpdates.



I think I will create an issue on react-native repo, what do you think ?

**Comment by Mokto** [comment]
Closing this one in favour of #77

**Comment by hyperh** [comment]
@Mokto Yea perhaps an issue on react-native repo would help. I'm having trouble understanding this error as well.

**Comment by txs** [comment]
Have you solve the issue? @hyperh
