### ISSUE TITLE
[Android] Unable to get cookie from the https://myapp.com/websocket

### ISSUE THREAD

**Issue by Mokto** [inProgress-team/react-native-meteor#77]
@hyperh

Has someone any idea why ?

**Comment by hyperh** [comment]
@Mokto I tried commenting out the line https://github.com/inProgress-team/react-native-meteor/blob/master/src/Data.js#L7, since it's just for performance reasons and is optional in minimongo-cache anyways. I still get the cookie error. I wonder if it's something else that's causing this.

**Comment by spencercarli** [comment]
Running into this as well. I'll see if I can find anything...

looks like websockets may have broken in 0.26? https://github.com/facebook/react-native/issues/7871

**Comment by spencercarli** [comment]
possible related? https://github.com/facebook/react-native/blob/a16dad33a635fc4cb27c8d009578e1a2f4adb793/docs/Troubleshooting.md#module-that-uses-websocket-such-as-firebase-throws-an-exception

**Comment by spencercarli** [comment]
I'm thinking it's related to this PR somehow https://github.com/facebook/react-native/pull/6851

The code that was reverted seems to have made it into 0.26... might be a reason. Anyways it seems that WebSocketModule.java is where the issues are coming from.

**Comment by Mokto** [comment]
Thanks for your research. I think you should ping react-native team on one of the issues regarding this.

Looking forward to seeing this fixed. Maybe 0.26.3 (just released few hours ago) will fix this ?

**Comment by spencercarli** [comment]
0.26.3 doesn't change anything but I did find a fix...

Change your server url from `https://myapp.com/websocket` or `http://myapp.com/websocket`

to `wss://myapp.com/websocket` or `ws://myapp.com/websocket`

Then it works! At least for me

**Comment by Victordmdb** [comment]
@spencercarli this worked for me, thanks!

**Comment by Mokto** [comment]
Thanks @spencercarli it works !!!

I just updated readme to help other people.
