### ISSUE TITLE
Meteor.status() is not reactive

### ISSUE THREAD

**Issue by fermuch** [inProgress-team/react-native-meteor#78]
The docs list `Meteor.status()` as a reactive source, but...

```jsx
import { Component } from 'react';
import { Text } from 'react-native';
import Meteor, { createContainer } from 'react-native-meteor';


class Status extends Component {
  render() {
    const { status } = this.props;

    return (
      <Text>{status}</Text>
    );
  }
}

export default createContainer(params=>{
  return {
    status: Meteor.status().status,
  };
}, Status)
```

This never triggers a re-render, but setting a timeout with a `console.log(Meteor.status())` to test if the status is updated shows the status being updated.

**Comment by Mokto** [comment]
Can you please test if this works with Meteor.status().connected please ?

**Comment by fermuch** [comment]
```javascript
console.info(isConnected, Meteor.status());
```

![terminal](http://i.imgur.com/NbokVIU.png)

And no re-runs are executed.
----

If I do something else inside the function, like subscribing to a collection, the function is re-called reactively.

**Comment by Mokto** [comment]
Can you please test this with rc8 ?

**Comment by fermuch** [comment]
It is working now! :+1:
