### ISSUE TITLE
Failed to install react-native-meteor 1.0.0 Beta 

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#8]
Error 504 on fetching npm registry:

while doing this:
<img width="569" alt="2016-03-02_1103" src="https://cloud.githubusercontent.com/assets/2161622/13450305/6a460530-e066-11e5-91bf-391f0ad71e96.png">

**Comment by Mokto** [comment]
Sorry, first beta out with npm.

I must have made an error but I will fix it tomorrow. It is late in Montréal, Canada ^^

**Comment by radiegtya** [comment]
Ok thanks @Mokto , please tell me if it already fixed.

**Comment by Mokto** [comment]
It seems like it is working now.

Is it ok for you ?

**Comment by radiegtya** [comment]
Yeah me too, I am now able to install it. I'll try and close this for now. Thanks
