### ISSUE TITLE
Disconnected from DDP server

### ISSUE THREAD

**Issue by sammkj** [inProgress-team/react-native-meteor#80]
Hello, thank you for creating this awesome package! I just started to explore RN with your package. I keep getting:

```
Meteor.js:115 Disconnected from DDP server.
```
Any pointers or guidance to solve this would be greatly appreciated!

**Comment by Mokto** [comment]
Hi,

1) Is your meteor server started ?
2) Are you running from device ?
3) If so, are connected on the same IP than your computer running the server ?
4) How did you connect to the meteor server ?

**Comment by sammkj** [comment]
1. Yeap! I'm very sure.
2. Nope, running the app from emulator
3. -
4. I just did `Meteor.connect('ws://localhost:3000/websocket');`

**Comment by sammkj** [comment]
I created a clean project and I still got the same error:

Steps:
1. create a new RN app
2. `npm install --save react-native-meteor`
3. add below in `index.android.js`:
    ```
    import Meteor from 'react-native-meteor';
    Meteor.connect('ws://localhost:3000/websocket');
    ```
4. I see the error in my console.

**Comment by sammkj** [comment]
I tried running the example, I got the same error as well.

**Comment by Mokto** [comment]
Has anyone used a simulator with react-native-meteor ?
I must admit I only use real devices. I would be happy if someone helps me on this.

Maybe you need to set your real IP rather than localhost ?

**Comment by fermuch** [comment]
I use it from the emulator. You need to forward the port:

```bash
adb reverse tcp:3000 tcp:3000
```

I also forward 8081, the react-native packager port, but I'm not sure if it's needed.

**Comment by sammkj** [comment]
@Mokto , thank you for response!

@fermuch , man! you're life saver! I got it working now

**Comment by Mokto** [comment]
Thanks @fermuch !

I just added your tip to detailled installation instructions.

**Comment by PolGuixe** [comment]
@fermuch Should I run `adb reverse tcp:3000 tcp:3000`everytime I am using the emulator or is there a way to set-up this in Android Studio AVD manager?

@Mokto How you do it with real devices? Do you add the local ip address of the development machine?

**Comment by Mokto** [comment]
With real devices, I'm connected to the same wi-fi network on both computer and device. So I set my IP address to something like : Meteor.connect('ws://192.168.X.X:3000/websocket');

**Comment by fermuch** [comment]
> @fermuch Should I run adb reverse tcp:3000 tcp:3000everytime I am using the emulator or is there a way to set-up this in Android Studio AVD manager?

I don't use Android Studio, so I'm not sure. I use an alias in my shell to first forward the ports and then use react-native start.

**Comment by donedgardo** [comment]
Hello, maybe i should open a new topic, but my issue might be related.

Im running on device too, and my Meteor.connect('xxxx') is pointing to productions server where my meteor app is running.
When i disconnect device from wifi it goes from `Connected to DDP server` to --> `Disconnected from DDP server`.

How do i manage to move this to production.

**Comment by Mokto** [comment]
Hi @donedgardo,

If I understand well your issue, it is the expected behaviour ;)

**Comment by funkyeah** [comment]
@donedgardo Is your device still connected to the web via cellular data?

**Comment by donedgardo** [comment]
Once I disable wifi on device it falls back to LTE network. Once I do this, My app doesn't connect to the server via ddp. If this is intended @Mokto, what you mean is that this package won't work on cellphones without wifi?

**Comment by masterSean** [comment]
@Mokto  Save me alot of time thanks!

**Comment by nyxynyx** [comment]
Saved me!!! +1 +2 +3

**Comment by derekgreenberg** [comment]
Thank you @fermuch!

**Comment by charlesdeb** [comment]
For others struggling to get access to the local Mongo database and meteor server on Windows 10, first run ```ipconfig``` to get the different ip addresses of your local machine, and then:

#### GenyMotion Android Emulator
Use the IP address of the VirtualBox host-only. I had to use the second one of the two addresses provided. My connection string was:
```ws://192.168.236.2:3000/websocket```

#### Real Android device
Use the IP address of your machine on the LAN - either the WiFi or ethernet adapter. My connection string was:
```ws://192.168.0.24:3000/websocket```

In neither case was I able to successfully use the wss protocol in my install.

**Comment by charlesdeb** [comment]
I managed to get my GenyMotion Android app emulator running on Windows 10 connecting to a local version of meteor by running ipconfig, and using the second IP address reserved for the virtual box. In my case it was:

ws://192.168.236.2:3000/websocket

But your exact IP address will be slightly different. I also managed to get it working on a real Android device, but needed to use the IP address of my laptop on the LAN. In neither case was I able to get it to connect using the wss protocol.

**Comment by bsbechtel** [comment]
I was having this issue with the Android emulator, but every time I make changes to the codebase, I have to rebuild the project. Does anyone know how to get it working with hot reloading so I don't have to rebuild the app every time in Android Studio?
