### ISSUE TITLE
Unable to Resolve Module react-mixin in react-native-meteor 1.0.0-beta

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#9]
I think you need to add this on Readme
```
npm install --save react-mixin
```

but anyway after I had installed that plugin, the error still there.
Any suggestion?

**Comment by Mokto** [comment]
I juste removed react-mixin dependency and exposed a connectMeteor decorator (see documentation).


Feel free to re-open if there is any issue remaining.
