### ISSUE TITLE
[Question] - react-native-meteor along side Redux

### ISSUE THREAD

**Issue by celloudiallo** [inProgress-team/react-native-meteor#90]
Hi,

I am considering combining react-native-meteor and redux... having redux actions responsible of calling meteor to fetch data and handle all my state via the redux store.

Have you tried this approach before?

Any drawback or inconvenient that you can think of?

thanks

**Comment by jacklam718** [comment]
I am also considering this problem.

**Comment by donedgardo** [comment]
Hey guys, I been working with this boilerplate that explains how to redux with meteor and react-native redux https://github.com/abhiaiyer91/How-We-Redux-Todos hope it helps.

**Comment by Mokto** [comment]
No I haven't, but using [react-komposer](https://github.com/kadirahq/react-komposer)/mantra should probably help you compose redux connect and meteor createContainer.

Closing this topic but feel free to discuss about this.
