### ISSUE TITLE
A better container designed for performance [tip]

### ISSUE THREAD

**Issue by grsabreu** [inProgress-team/react-native-meteor#93]
Hi guys! First of all, thank you for all the great work on react-native-meteor.
This is the container I'm talking about: https://github.com/Astrocoders/rn-meteor-containerize

This is my team little help for the Meteor community who uses react-native-meteor.
As we faced some performance issues, especially during Navigator transitions and subscriptions happening at once.
So we created a container which will just run the Meteor data code after any UI heavy task, ensuring smooth transactions every time.

If you like it, I can send a PR writing a bit about it in the react-native-meteor README file.

**Comment by funkyeah** [comment]
Hey @grsabreu, I really like the idea about making things faster. I'm having a little trouble fully understanding how it works or where it helps.

Is the basic premise that doing a subscription in getMeteorData() tends to be a long running task, and this improves performance by defering it to after animations are complete?

Couple questions:
1. What is an example scenario where this would really help speed things up? Other Pros?
2. Are there any Cons you can things of?
3. I thought subscription functions pretty much returned right away with a the subscription ID... do you know what long running aspect you are trying to defer
4. createContainer and the [react-meteor-data](https://atmospherejs.com/meteor/react-meteor-data) package is what MDG is pushing, and what this library has already implemented for a container component... would it be easy to apply this same speed-up technique to the createContainer function?

**Comment by smooJitter** [comment]
I assume this is for RN built via a mantra framework?

**Comment by grsabreu** [comment]
@funkyeah thanks for the feedback, I'll be glad to answer:

1. It helps smoother transition for Navigator routes, so when you transition to another route subscribing right away to a publication will make the component re-render which can slow down your transition animation sometimes.
2. I can't think in any cons, it works just like react-komposer. So you can even compose then with their `composeAll` API.
3. I don't understood very well this question of yours, but you mean that subscriptions return right away they first data after subscribing?
4. Yes! Would be fine to do the same performances assurances to the `createContainer`. I don't remember why I don't made with it straightaway, I think I had some composing issues, but seems fine to be done now.

I can take a time to put an example application in the lib repo to show better the differences of performance.

**Comment by grsabreu** [comment]
@smooJitter no! you can you straightaway with any RN set you have

**Comment by Mokto** [comment]
Hi @grsabreu,

Thanks for your work.
I have been having issues with RNRF transitions too, so this PR would be much appreciated !!

:)

Closing this issue but feel free to discuss about it.

**Comment by grsabreu** [comment]
Hey, you can use it already! Just install the package and use it instead of `createContainer`.

```js
import composeWithtracker from 'rn-meteor-containerize'

function composer(props, onData){
  const handle = Meteor.subscribe('items') 

  if(handle.ready()){
    onData(null, {
      items: Meteor.collections('items').find({}),
    });  
  }
}

export default composeWithTracker(composer);
```

then use the container as you normally would
```js
...
import ItemsContainer from '/path/to/container';

const Foo = React.createClass({
 propTypes: { items: PropTypes.object },
 render(){
   // ...
 },
});

export default ItemContainer(Foo);
```

**Comment by Mokto** [comment]
Yes, but if it works well, I would like to pull it into react-native-meteor.

Would you mind creating a PR with theses changes ? ;)

**Comment by grsabreu** [comment]
Ok man! I'll create a PR ASAP!

**Comment by Tim-W** [comment]
@grsabreu any progress on this? :)

**Comment by grsabreu** [comment]
Hey @Tim-W meanwhile you can use the container directly from rn-meteor-containerize, the usage will be the same when it get into the react-native-meteor

**Comment by Tim-W** [comment]
@grsabreu I took a quick look at your the code from rn-meteor-containerize. So basically all you do is load the data in a InteractionManager.runAfterInteractions wrapper? 

It would be much better if we could use multithreading for this, and use something like a webworker to load the data in the background. I don't know if this is supported in React-Native, I'll find out.

**Comment by Tim-W** [comment]
Apparently multithreading/workers are not fully supported yet in RN. See https://github.com/NativeScript/android-runtime/issues/532 and https://github.com/NativeScript/ios-runtime/issues/620

**Comment by grsabreu** [comment]
Hey, @Tim-W! Thank you for the tips.
Unfortunately I'm running busy these days and couldn't work for the PR. But I'm going to have a free time in the end of this week and I plan to push some work on it.

Yes, basically I'm just wrapping the InteractionManager to avoid the computation of the subscriptions and etc. to mess with the coolness of our animations/transitions.
The idea of using workers seems interesting, I'm going to take a look on it.

**Comment by bhoomika911** [comment]
Hi grsabreu,

https://github.com/inProgress-team/react-native-meteor/pull/135

As per this link,rn-meteor-containerize has been integrated with react-native-meteor@1.0.3.I am using react-native-meteor@1.0.3 .But I am still facing issue in navigator transition in android.

Any one can help?
