### ISSUE TITLE
MeteorListView loading state

### ISSUE THREAD

**Issue by jakobloekke** [inProgress-team/react-native-meteor#97]
What's the best way to show the loading state of a MeteorListView? It needs handling, because otherwise the list items just jump around while loading data.

If I swap the component out for a <ActivityIndicator/> while !subscription.ready(), it breaks the [automaticallyadjustcontentinsets](https://facebook.github.io/react-native/docs/scrollview.html#automaticallyadjustcontentinsets) functionality when embedded in a NavigatorIOS. This means the list overlaps with the navigator element at the top.
It also overlaps with a bottom tabbar, if using that.

I've added a style={{opacity: this.props.loading ? 0 : 1}} for now and that works, but I'd really like to show a spinner somehow instead of just a blank screen.

Any ideas?

**Comment by Mokto** [comment]
Can you show your code please ?
