### ISSUE TITLE
MeteorListView scroll problem

### ISSUE THREAD

**Issue by sepehrooo** [inProgress-team/react-native-meteor#98]
I created a list view that loads correct but I can't scroll this list view even though the elements are more than one page.
You can see the clip I'll send to see the problem. In ios it will scroll and jumps at the start of list. In android it won't even scroll.

![problem](https://cloud.githubusercontent.com/assets/2351478/16504777/ea0cf8f6-3f2e-11e6-9a2e-7d954b69de1e.gif)

And this is how I render the listView:
`<View>
      <MeteorListView collection="items" renderRow={renderRow}/>
    </View>`
And this is the renderRow:
`<View>
    <Text>{item.text}</Text>
    </View>`

**Comment by Jarskih** [comment]
Add flex: 1 to the wrapping View. That worked for me.

**Comment by sepehrooo** [comment]
Thanks a lot @Jarskih.
