### ISSUE TITLE
Issues when using composeWithTracker with react-native-router-flux

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [inProgress-team/react-native-meteor#99]
Hello! I'm having some issues when u sing with react-native-router-flux
I think there are two critical points:

- When a scene changes, componentWillUnmount is not called, therefore, the function to stop the subscription is not called and the subscription does not stop.

- The Router is passing a lot of props to my components, so whenever I change routes, the function of all containers crated with komposer rerun because of props changes (I'm not sure about this, but I can confirm that they are rerunning because i'm console.loging inside the composer function)

This is causing performance issues on my app as I navigate throught my routes

Any ideas on how to fix this ?

More detailed info:

RestaurantesContainer.jsx
```js
function composer(props, onData) {
  console.log('--props on RestaurantesContainer---')
  console.log(props)
  const handle = Meteor.subscribe('restaurantes')
  const restaurantesFields = {
    fields: {
      logoUrl: 1,
      backgroundUrl: 1
    }
  }
  if (handle.ready()) {
    const restaurantes = Meteor.collection('restaurantes').find({}, restaurantesFields)
    onData(null, {
      restaurantes
    })
  }

  return handle.stop()
}

export default composeWithTracker(composer, Loading, Error)(RestaurantesList)
```

App.js
```js
class App extends Component {
  render() {
    return (
        <Router>
          <Scene key="drawer" component={DrawerContainer} menuItems={menuItems}>
            <Scene key="root" navBar={NavBar}>
              <Scene
                initial={true}
                key="restaurantes"
                title="Restaurantes"
                component={RestaurantesContainer} />
          </Scene> 
         </Scene>
       </Router>
     )
   }
}
```

**Comment by fermuch** [comment]
This is just a fast lookup, and I think it won't solve your issues, but `return handle.stop()` stops the subscription just as it is created.

You might want to change it to:

```jsx
return () => handle.stop()
```

**Comment by rafaelcorreiapoli** [comment]
I tried this too, but the problem is that the unmount lifecycle hook is never called

**Comment by fermuch** [comment]
I find it really weird, since I didn't have any problem desuscribing on the phone.
just as a quick test, does this return anything?

```jsx
if (handle.ready()) {
    const restaurantes = Meteor.collection('restaurantes').find({}, restaurantesFields)
    onData(null, {
      restaurantes
    })
  }

  return () => {
    console.info('I HAVE BEEN CALLED!');
    handle.stop();
  }
}
```

**Comment by rafaelcorreiapoli** [comment]
No, because react-native-router-flux does not unmount the components
I can see that message "I HAVE BEEN CALLED" when I Reload de the JS, because in that moment everything is unmounted

**Comment by rafaelcorreiapoli** [comment]
Ok, I fixed that by declaring my Scenes with type "replace"
